# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      # day: "monday"
      timezone: "Asia/Shanghai"
      time: "07:00"
    pull-request-branch-name:
      separator: "-"
      
    groups:
       all-actions:
         patterns:
           - "*"

    open-pull-requests-limit: 10
      
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      # day: "monday"
      timezone: "Asia/Shanghai"
      time: "07:00"
    pull-request-branch-name:
      separator: "-"
    
    groups:
       all-actions:
         patterns:
           - "*"

    open-pull-requests-limit: 10

    # commit-message:
      # prefix: "ci"
      # prefix-development: "ci"
      # include: "scope"

    # labels:
      # - "dependencies"
      # - "documentation"
