{       "简介": "&&",
        "二次截取": "class=\"row video-list video-film-list clearfix&&</ul>",
        "数组": "class=\"video-item&&class=\"video-con",
        "标题": "title=\"&&\"",
        "图片": "data-original=\"&&\"",
        "副标题": "🌲+duration\">&&</div>",
        "链接": "href=\"&&\"",
        "播放数组": "playlist-sort-content&&</ul>",
        "播放列表": "<a&&a>",
        "播放链接": "href=\"&&\"",
        "播放标题": "\">&&</",
        "线路数组": "class=\"swiper-slide ewave-tab&&li>",
        "线路标题": "💕+>&&</",
        "跳转播放链接": "var player_*\"url\":\"&&\"",
        "分类url": "https://www.sh-bridge.com/screen/{cateId}-{area}-{by}-{class}-{lang}-{letter}---{catePg}---{year}.html",
        "分类": "电影$1#电视剧$2#综艺$3#动漫$4#短剧$33"
      }
