{
    "站名": "天天综合",
    "发布页": "https://771267398.550xx.vip",
    "发布页2": "https://666sav.com",
    "主页url": "https://30kknn.vip",
    "直接播放": "1",
    "热门推荐": "1",
    "起始页": "1",
    "数组": "<a&&</a>",
    "图片": "data-original=\"&&\"",
    "标题": "title=\"&&\"",
    "链接": "href=\"&&\"",
    "链接前缀": "https://30kknn.vip",
    "副标题": "<div class=\"duration\">&&</div>",
    "嗅探词": ".m3u8#.mp4#.flv#.m4a#.avi#.mkv#.mov#.3gp#.asf#.rm#.rmvb#.wmv#.mpg#.mpeg#.mpe#.ts#.vob#.mp3#.wma",
    "搜索url": "/sos{wd}/page/{catePg}.html",
    "分类": "中文资源$xjzy/#超清资源$cq/#AV解说$avjs/#国产传媒$gccm/#久久热$99re/#废材网$fcw/",
    "分类url": "https://30kknn.vip/{cateId}-{catePg}.html[https://30kknn.vip/{cateId}]",
    "筛选": {
        "gccm/": [{
            "key": "cateId",
            "name": "",
            "value": [{
                "n": "全部",
                "v": ""
            }, {
                "n": "麻豆传媒",
                "v": "gccm/91-madouyuanchuang"
            }, {
                "n": "91制片厂",
                "v": "gccm/91-91zhipianchang"
            }, {
                "n": "杏吧原创",
                "v": "gccm/91-xingbayuanchuang"
            }, {
                "n": "糖心Vlgo",
                "v": "gccm/91-tangxinVlgo"
            }, {
                "n": "天美传媒",
                "v": "gccm/91-tianmeichuanmei"
            }, {
                "n": "蜜桃传媒",
                "v": "gccm/91-mitaochuanmei"
            }, {
                "n": "星空传媒",
                "v": "gccm/91-xingkongchuanmei"
            }, {
                "n": "精东影业",
                "v": "gccm/91-jingdongyingye"
            }, {
                "n": "兔子先生",
                "v": "gccm/91-tuzixiansheng"
            }, {
                "n": "大象传媒",
                "v": "gccm/91-daxiangchuanmei"
            }]
        }],
        "avjs/": [{
            "key": "cateId",
            "name": "",
            "value": [{
                "n": "全部",
                "v": ""
            }, {
                "n": "解说原片",
                "v": "xjzy/cn-jieshuoyuanpian"
            }, {
                "n": "水果解说",
                "v": "avjs/sgp-AVJS"
            }]
        }],
        "99re/": [{
            "key": "cateId",
            "name": "",
            "value": [{
                "n": "全部",
                "v": ""
            }, {
                "n": "国产自拍",
                "v": "99re/kdw-guochanzipai"
            }, {
                "n": "欧美",
                "v": "99re/kdw-oumei"
            }, {
                "n": "中文字幕",
                "v": "99re/kdw-zhongwenzimu"
            }, {
                "n": "李宗瑞全集",
                "v": "99re/kdw-lizongruiquanji"
            }, {
                "n": "日本无码",
                "v": "99re/kdw-ribenwuma"
            }, {
                "n": "加勒比",
                "v": "99re/kdw-jialebi"
            }, {
                "n": "日本有码",
                "v": "99re/kdw-ribenyouma"
            }, {
                "n": "一本道",
                "v": "99re/kdw-yibendao"
            }, {
                "n": "高清",
                "v": "99re/kdw-gaoqing"
            }, {
                "n": "潮吹",
                "v": "99re/kdw-chaochui"
            }]
        }, {
            "key": "cateId",
            "name": "",
            "value": [{
                "n": "全部",
                "v": ""
            }, {
                "n": "成人动漫",
                "v": "99re/kdw-chengrendongman"
            }, {
                "n": "会员认证作品",
                "v": "99re/kdw-jiujiurehuiyuanrenzhengzuopin"
            }, {
                "n": "制服丝袜",
                "v": "99re/kdw-zhifusiwa"
            }, {
                "n": "口爆颜射",
                "v": "99re/kdw-koubaoyanshe"
            }, {
                "n": "肛交",
                "v": "99re/kdw-gangjiao"
            }, {
                "n": "东京热",
                "v": "99re/kdw-dongjingre"
            }, {
                "n": "小格式综合",
                "v": "99re/kdw-xiaogeshizonghe"
            }, {
                "n": "主播系列",
                "v": "99re/kdw-hanguonvzhuboxilie"
            }, {
                "n": "SM性虐",
                "v": "99re/kdw-SMxingnue"
            }, {
                "n": "韩国综合",
                "v": "99re/kdw-hanguozonghe"
            }]
        }],
        "fcw/": [{
            "key": "cateId",
            "name": "",
            "value": [{
                "n": "全部",
                "v": ""
            }, {
                "n": "VIP专区",
                "v": "fcw/ff-VIPzhuanqu"
            }, {
                "n": "偷拍系列",
                "v": "fcw/ff-toupaixilie"
            }, {
                "n": "国产自拍",
                "v": "fcw/ff-guochanzipai"
            }, {
                "n": "日本有码",
                "v": "fcw/ff-ribenyouma"
            }, {
                "n": "日本无码",
                "v": "fcw/ff-ribenwuma"
            }, {
                "n": "成人动漫",
                "v": "fcw/ff-chengrendongman"
            }, {
                "n": "韩国综合",
                "v": "fcw/ff-hanguozonghe"
            }, {
                "n": "VR专区",
                "v": "fcw/ff-VRzhuanqu"
            }, {
                "n": "欧美",
                "v": "fcw/ff-oumei"
            }]
        }],
        "cq/": [{
            "key": "cateId",
            "name": "",
            "value": [{
                "n": "全部",
                "v": ""
            }, {
                "n": "亚洲AV",
                "v": "cq/2k-yazhou"
            }, {
                "n": "自拍偷拍",
                "v": "cq/2k-zipaitoupai"
            }, {
                "n": "超清传媒",
                "v": "cq/2k-chaoqingchuanmei"
            }, {
                "n": "3D动漫",
                "v": "cq/2k-3Ddongman"
            }, {
                "n": "欧美AV",
                "v": "cq/2k-oumei"
            }, {
                "n": "乱伦人妻",
                "v": "cq/2k-luanlunrenqi"
            }, {
                "n": "丝袜制服",
                "v": "cq/2k-siwazhifu"
            }, {
                "n": "直播录播",
                "v": "cq/2k-zhibolubo"
            }, {
                "n": "SM另类",
                "v": "cq/2k-SMlinglei"
            }, {
                "n": "超清三级",
                "v": "cq/2k-chaoqingsanji"
            }]
        }],
        "xjzy/": [{
            "key": "cateId",
            "name": "",
            "value": [{
                "n": "全部",
                "v": ""
            }, {
                "n": "3D同人",
                "v": "xjzy/cn-3Dtongren"
            }, {
                "n": "中文无码",
                "v": "xjzy/cn-zhongwenwuma"
            }, {
                "n": "中文综合",
                "v": "xjzy/cn-zhongwenzonghe"
            }, {
                "n": "中文近亲",
                "v": "xjzy/cn-zhongwenjingqing"
            }, {
                "n": "中文护士",
                "v": "xjzy/cn-zhongwenhushi"
            }, {
                "n": "中文师生",
                "v": "xjzy/cn-zhongwenshisheng"
            }, {
                "n": "中文强奸",
                "v": "xjzy/cn-zhongwenqiangjian"
            }, {
                "n": "明星淫梦",
                "v": "xjzy/cn-mingxingyinmeng"
            }, {
                "n": "国产自拍",
                "v": "xjzy/cn-guochanzipai"
            }, {
                "n": "三级伦理",
                "v": "xjzy/cn-sanjizonghe"
            }]
        }]
    }
}