{
"站名":"综合直播",
"主页url":"https://ttszb9.com",
"直接播放":"1",
"数组":"<a&&</a>",
"图片":"data-original=\"&&\"",
"标题":"title=\"&&\"",
"链接":"href=\"&&\"",
"链接前缀":"https://ttszb9.com",
"副标题":"<div class=\"duration\">&&</div>",
"分类":"亚洲$yzzb/zb/gwzb#中文$yzzb/zb/cnzb#日本$yzzb/zb/ryzb#越南$yzzb/zb/yyzb#俄国$yzzb/zb/egzb#乌克兰$yzzb/zb/wkl#欧美$yzzb/zb/omzb#更多筛选$xxj/zb/kwy",
"分类url":"https://ttszb9.com/?vip={cateId}.html",
"免嗅":"0",
"嗅探词":".m3u8#.mp4#.flv#.m4a#.avi#.mkv#.mov#.3gp#.asf#.rm#.rmvb#.wmv#.mpg#.mpeg#.mpe#.ts#.vob#.mp3#.wma",
"筛选":{
"xxj/zb/kwy":[
{
"key":"cateId",
"name":"",
"value":[
{"n":"卡哇伊","v":"xxj/zb/kwy"},
{"n":"咪狐直播","v":"xxj/zb/mh"},
{"n":"蜜桃直播","v":"xxj/zb/mt"},
{"n":"小妲己","v":"xxj/zb/xdj"},
{"n":"LOVE直播","v":"xxj/zb/love"},
{"n":"番茄直播","v":"xxj/zb/fq"},
{"n":"77直播","v":"xxj/zb/qq"},
{"n":"依依直播","v":"xxj/zb/yy"},
{"n":"日出直播","v":"xxj/zb/rc"},
{"n":"彩虹直播","v":"xxj/zb/ch"},
{"n":"久久直播","v":"xxj/zb/jj"}
]
},
{
"key":"cateId",
"name":"",
"value":[
{"n":"亚米直播","v":"xxj/zb/ym"},
{"n":"恋蝶直播","v":"xxj/zb/ld"},
{"n":"夜妖姬","v":"xxj/zb/yyj"},
{"n":"套路直播","v":"xxj/zb/tl"},
{"n":"樱花直播","v":"xxj/zb/yh"},
{"n":"享色直播","v":"xxj/zb/xs"},
{"n":"红浪漫","v":"xxj/zb/hlm"},
{"n":"金鱼直播","v":"xxj/zb/jy"},
{"n":"桃花直播","v":"xxj/zb/th"},
{"n":"花房直播","v":"xxj/zb/hf"},
{"n":"小仙女","v":"xxj/zb/xxn"}
]
},
{
"key":"cateId",
"name":"",
"value":[
{"n":"视觉秀","v":"xxj/zb/sjx"},
{"n":"小天使","v":"xxj/zb/xts"},
{"n":"彩云直播","v":"xxj/zb/cy"},
{"n":"咪咪直播","v":"xxj/zb/mm"},
{"n":"娇媚直播","v":"xxj/zb/jm"},
{"n":"黄瓜直播","v":"xxj/zb/hg"},
{"n":"色趣直播","v":"xxj/zb/sq"},
{"n":"糯米直播","v":"xxj/zb/nm"},
{"n":"小蜜蜂","v":"xxj/zb/xmf"},
{"n":"小红帽","v":"xxj/zb/xhm"},
{"n":"桃花运","v":"xxj/zb/thy"}
]
},
{
"key":"cateId",
"name":"",
"value":[
{"n":"苦瓜直播","v":"xxj/zb/kg"},
{"n":"爱爱你","v":"xxj/zb/aan"},
{"n":"樱花雨","v":"xxj/zb/yh"},
{"n":"盘他直播","v":"xxj/zb/pt"},
{"n":"夜色直播","v":"xxj/zb/ys"},
{"n":"蝴蝶直播","v":"xxj/zb/hd"},
{"n":"小天仙","v":"xxj/zb/xtx"},
{"n":"杏趣直播","v":"xxj/zb/xq"},
{"n":"小坏蛋","v":"xxj/zb/xhd"},
{"n":"飘雪直播","v":"xxj/zb/px"},
{"n":"樱桃直播","v":"xxj/zb/yt"}
]
},
{
"key":"cateId",
"name":"",
"value":[
{"n":"奥斯卡","v":"xxj/zb/ask"},
{"n":"兔女郎","v":"xxj/zb/tnl"},
{"n":"花仙子","v":"xxj/zb/hxz"},
{"n":"小性感","v":"xxj/zb/xxg"},
{"n":"蓝月亮","v":"xxj/zb/lyl"},
{"n":"名流直播","v":"xxj/zb/ml"},
{"n":"情趣直播","v":"xxj/zb/qqu"},
{"n":"牵手直播","v":"xxj/zb/qs"},
{"n":"蚊香社","v":"xxj/zb/wxs"},
{"n":"杏播直播","v":"xxj/zb/xb"},
{"n":"喜欢你","v":"xxj/zb/xhn"}
]
},
{
"key":"cateId",
"name":"",
"value":[
{"n":"小辣椒直播","v":"xxj/zb/xlj"},
{"n":"小精灵直播","v":"xxj/zb/xjl"},
{"n":"小棉袄直播","v":"xxj/zb/xma"}
]
}
]
}
}
