台灣頻道,#genre#
民視,http://foxtv.zone.id/ublive.php?id=336
民視,http://foxtv.zone.id/ublive.php?id=2805
台視,http://foxtv.zone.id/ublive.php?id=326
台視,http://foxtv.zone.id/ublive.php?id=312
中視,http://foxtv.zone.id/ublive.php?id=333
中視,http://foxtv.zone.id/ublive.php?id=1041
華視,http://foxtv.zone.id/ublive.php?id=32
華視,http://foxtv.zone.id/ublive.php?id=2282
公視,http://foxtv.zone.id/ublive.php?id=86
公視,http://foxtv.zone.id/ublive.php?id=28
好消息,http://foxtv.zone.id/ublive.php?id=104
客家電視,http://foxtv.zone.id/ublive.php?id=76
緯來綜合,http://foxtv.zone.id/ublive.php?id=2726
八大第一,http://foxtv.zone.id/ublive.php?id=318
八大綜合,http://foxtv.zone.id/ublive.php?id=3258
八大綜合,http://foxtv.zone.id/ublive.php?id=2286
三立臺灣,http://foxtv.zone.id/ublive.php?id=35
三立臺灣,http://foxtv.zone.id/ublive.php?id=2436
三立臺灣,http://foxtv.zone.id/ublive.php?id=21
三立都會,http://foxtv.zone.id/ublive.php?id=2435
三立都會,http://foxtv.zone.id/ublive.php?id=1001
三立都會,http://foxtv.zone.id/ublive.php?id=38
東森綜合,http://foxtv.zone.id/ublive.php?id=372
東森綜合-替,http://foxtv.zone.id/ublive.php?id=3254
東森超視,http://foxtv.zone.id/ublive.php?id=80
東森購物2,http://foxtv.zone.id/ublive.php?id=1156
中天綜合,http://foxtv.zone.id/ublive.php?id=3072
中天綜合,http://foxtv.zone.id/ublive.php?id=54
中天娛樂,http://foxtv.zone.id/ublive.php?id=324
TVBS歡樂,http://foxtv.zone.id/ublive.php?id=40
八大精彩,http://foxtv.zone.id/ublive.php?id=1024
JET綜合,http://foxtv.zone.id/ublive.php?id=41
東森購物1,http://foxtv.zone.id/ublive.php?id=1155
TVBS,http://foxtv.zone.id/ublive.php?id=2273
TVBS,http://foxtv.zone.id/ublive.php?id=16
緯來育樂,http://foxtv.zone.id/ublive.php?id=338
緯來育樂（測試）,http://foxtv.zone.id/ublive.php?id=2772
緯來日本-1,http://foxtv.zone.id/ublive.php?id=337
緯來日本（備）,http://foxtv.zone.id/ublive.php?id=46
緯來日本,http://foxtv.zone.id/ublive.php?id=3266
國興衛視,http://foxtv.zone.id/ublive.php?id=65
信大電視,http://foxtv.zone.id/ublive.php?id=422
八大娱乐,http://foxtv.zone.id/ublive.php?id=105
公視3台,http://foxtv.zone.id/ublive.php?id=1340
好消息2,http://foxtv.zone.id/ublive.php?id=363
高點綜合,http://foxtv.zone.id/ublive.php?id=99
中天亞洲,http://foxtv.zone.id/ublive.php?id=2277
中天亞洲,http://foxtv.zone.id/ublive.php?id=322
民視第一台,http://foxtv.zone.id/ublive.php?id=3272
民視台灣,http://foxtv.zone.id/ublive.php?id=36
龍華日韓,http://foxtv.zone.id/ublive.php?id=382
豬哥會社,http://foxtv.zone.id/ublive.php?id=103
ELTA娛樂台,http://foxtv.zone.id/ublive.php?id=351
韓國娛樂,http://foxtv.zone.id/ublive.php?id=73
靖天國際,http://foxtv.zone.id/ublive.php?id=345
靖天育樂,http://foxtv.zone.id/ublive.php?id=1029
靖天日本,http://foxtv.zone.id/ublive.php?id=108
靖天歡樂,http://foxtv.zone.id/ublive.php?id=51
三立綜合,http://foxtv.zone.id/ublive.php?id=315
三立綜合,http://foxtv.zone.id/ublive.php?id=2815
靖天資訊,http://foxtv.zone.id/ublive.php?id=49
中視經典,http://foxtv.zone.id/ublive.php?id=185
中視菁采,http://foxtv.zone.id/ublive.php?id=74
TVBS精采,http://foxtv.zone.id/ublive.php?id=66
年代much,http://foxtv.zone.id/ublive.php?id=1359
ELTA綜合,http://foxtv.zone.id/ublive.php?id=1137
東森購物3,http://foxtv.zone.id/ublive.php?id=1584
MOMO購物1,http://foxtv.zone.id/ublive.php?id=1585
MOMO購物2,http://foxtv.zone.id/ublive.php?id=1586
美好購物1,http://foxtv.zone.id/ublive.php?id=1591
美好購物2,http://foxtv.zone.id/ublive.php?id=1592
大立電視,http://foxtv.zone.id/ublive.php?id=1593
國會頻道１,http://foxtv.zone.id/ublive.php?id=2614
國會頻道2,http://foxtv.zone.id/ublive.php?id=420
海豚綜合,http://foxtv.zone.id/ublive.php?id=262
台灣地震監視,http://foxtv.zone.id/ublive.php?id=2637
誠心電視,http://foxtv.zone.id/ublive.php?id=495
萬秀豬王,http://foxtv.zone.id/ublive.php?id=2978
三立新聞,http://foxtv.zone.id/ublive.php?id=43
三立新聞-2,http://foxtv.zone.id/ublive.php?id=2794
三立新聞,http://foxtv.zone.id/ublive.php?id=2392
三立新聞+,http://foxtv.zone.id/ublive.php?id=320
東森新聞,http://foxtv.zone.id/ublive.php?id=1025
東森新聞4,http://foxtv.zone.id/ublive.php?id=2766
東森新聞,http://foxtv.zone.id/ublive.php?id=2393
東森亞洲,http://foxtv.zone.id/ublive.php?id=3
中天新聞2,http://foxtv.zone.id/ublive.php?id=2420
中天新聞2台,http://foxtv.zone.id/ublive.php?id=152
民視新聞,http://foxtv.zone.id/ublive.php?id=2395
TVBS新聞,http://foxtv.zone.id/ublive.php?id=2736
TVBS新聞,http://foxtv.zone.id/ublive.php?id=2396
東森財經,http://foxtv.zone.id/ublive.php?id=2397
華視新聞-2,http://foxtv.zone.id/ublive.php?id=2424
三立iNEWS-2,http://foxtv.zone.id/ublive.php?id=6
台視新聞,http://foxtv.zone.id/ublive.php?id=2399
台視新聞,http://foxtv.zone.id/ublive.php?id=1
中視新聞,http://foxtv.zone.id/ublive.php?id=2400
寰宇新聞台灣,http://foxtv.zone.id/ublive.php?id=2401
寰宇新聞,http://foxtv.zone.id/ublive.php?id=304
寰宇財經,http://foxtv.zone.id/ublive.php?id=2536
公視新聞,http://foxtv.zone.id/ublive.php?id=20
寰宇臺灣,http://foxtv.zone.id/ublive.php?id=87
年代新聞,http://foxtv.zone.id/ublive.php?id=2719
壹新聞,http://foxtv.zone.id/ublive.php?id=2777
年代新聞-備,http://foxtv.zone.id/ublive.php?id=1099
台視財經,http://foxtv.zone.id/ublive.php?id=300
鏡新聞mnews,http://foxtv.zone.id/ublive.php?id=463
三立国際,http://foxtv.zone.id/ublive.php?id=2285
CBN News,http://foxtv.zone.id/ublive.php?id=499
東森戲劇,http://foxtv.zone.id/ublive.php?id=2825
東森戲劇-備,http://foxtv.zone.id/ublive.php?id=321
八大戲劇,http://foxtv.zone.id/ublive.php?id=81
緯來戲劇,http://foxtv.zone.id/ublive.php?id=2727
緯來戲劇-備,http://foxtv.zone.id/ublive.php?id=339
東森電影,http://foxtv.zone.id/ublive.php?id=350
東森電影,http://foxtv.zone.id/ublive.php?id=2720
緯來電影,http://foxtv.zone.id/ublive.php?id=2728
緯來電影,http://foxtv.zone.id/ublive.php?id=3252
HBO HD,http://foxtv.zone.id/ublive.php?id=332
HBO HD,http://foxtv.zone.id/ublive.php?id=2823
東森洋片,http://foxtv.zone.id/ublive.php?id=1128
壹電影,http://foxtv.zone.id/ublive.php?id=2284
好萊塢電影,http://foxtv.zone.id/ublive.php?id=37
愛爾達影劇,http://foxtv.zone.id/ublive.php?id=500
CineMAX,http://foxtv.zone.id/ublive.php?id=346
緯來精彩,http://foxtv.zone.id/ublive.php?id=2280
EYE戲劇,http://foxtv.zone.id/ublive.php?id=191
三立戲劇,http://foxtv.zone.id/ublive.php?id=64
三立戲劇,http://foxtv.zone.id/ublive.php?id=2819
龍華偶像,http://foxtv.zone.id/ublive.php?id=385
霹靂臺灣,http://foxtv.zone.id/ublive.php?id=1339
美亞電影,http://foxtv.zone.id/ublive.php?id=375
HBOSignature,http://foxtv.zone.id/ublive.php?id=329
HBOSignature,http://foxtv.zone.id/ublive.php?id=2824
HBO Hits,http://foxtv.zone.id/ublive.php?id=330
采昌影劇,http://foxtv.zone.id/ublive.php?id=2804
影迷數位電影,http://foxtv.zone.id/ublive.php?id=2800
龍華戲劇,http://foxtv.zone.id/ublive.php?id=2796
龍華經典,http://foxtv.zone.id/ublive.php?id=100
龍翔時代,http://foxtv.zone.id/ublive.php?id=373
AXN臺灣,http://foxtv.zone.id/ublive.php?id=2816
天映經典,http://foxtv.zone.id/ublive.php?id=2289
AXN亞洲,http://foxtv.zone.id/ublive.php?id=1066
Trill恐怖電影,http://foxtv.zone.id/ublive.php?id=18
龍華電影,http://foxtv.zone.id/ublive.php?id=311
華納電影,http://foxtv.zone.id/ublive.php?id=83
龍華洋片,http://foxtv.zone.id/ublive.php?id=341
飢餓遊戲,http://foxtv.zone.id/ublive.php?id=264
緯來體育,http://foxtv.zone.id/ublive.php?id=118
緯來體育,http://foxtv.zone.id/ublive.php?id=2732
ELTA體育1,http://foxtv.zone.id/ublive.php?id=192
ELTA體育1,http://foxtv.zone.id/ublive.php?id=2729
ELTA體育2,http://foxtv.zone.id/ublive.php?id=2730
ELTA體育2,http://foxtv.zone.id/ublive.php?id=193
ELTA體育3,http://foxtv.zone.id/ublive.php?id=2731
ELTA體育3,http://foxtv.zone.id/ublive.php?id=194
ELTA體育4,http://foxtv.zone.id/ublive.php?id=2820
ELTA體育4-備,http://foxtv.zone.id/ublive.php?id=3255
Eleven Sport 1,http://foxtv.zone.id/ublive.php?id=3224
Eleven Sport 2,http://foxtv.zone.id/ublive.php?id=301
Z頻道,http://foxtv.zone.id/ublive.php?id=1130
博斯無限,http://foxtv.zone.id/ublive.php?id=381
博斯無限,http://foxtv.zone.id/ublive.php?id=2797
博斯無限2,http://foxtv.zone.id/ublive.php?id=426
博斯無限2,http://foxtv.zone.id/ublive.php?id=2798
博斯運動1,http://foxtv.zone.id/ublive.php?id=379
博斯運動2,http://foxtv.zone.id/ublive.php?id=380
亞洲旅遊,http://foxtv.zone.id/ublive.php?id=2299
探索頻道,http://foxtv.zone.id/ublive.php?id=2817
探索頻道,http://foxtv.zone.id/ublive.php?id=1035
大陸尋奇,http://foxtv.zone.id/ublive.php?id=102
動物星球,http://foxtv.zone.id/ublive.php?id=367
探索亞洲,http://foxtv.zone.id/ublive.php?id=306
探索科學,http://foxtv.zone.id/ublive.php?id=343
探索科學-2,http://foxtv.zone.id/ublive.php?id=3275
國家野生（英）,http://foxtv.zone.id/ublive.php?id=1038
探索EVE,http://foxtv.zone.id/ublive.php?id=1036
視納華仁紀實,http://foxtv.zone.id/ublive.php?id=91
美食星球,http://foxtv.zone.id/ublive.php?id=3073
美食星球,http://foxtv.zone.id/ublive.php?id=1360
EYE旅遊,http://foxtv.zone.id/ublive.php?id=1494
探索動力DMAX,http://foxtv.zone.id/ublive.php?id=335
Globetrotter（MOD）,http://foxtv.zone.id/ublive.php?id=3259
MOMO親子,http://foxtv.zone.id/ublive.php?id=2767
東森幼幼,http://foxtv.zone.id/ublive.php?id=371
東森幼幼,http://foxtv.zone.id/ublive.php?id=2771
東森亞洲呦呦,http://foxtv.zone.id/ublive.php?id=293
CN卡通,http://foxtv.zone.id/ublive.php?id=107
靖天卡通,http://foxtv.zone.id/ublive.php?id=344
大愛一臺,http://foxtv.zone.id/ublive.php?id=11
港澳頻道,#genre#
TVB翡翠,http://foxtv.zone.id/ublive.php?id=390
TVB翡翠,http://foxtv.zone.id/ublive.php?id=30
TVB明珠,http://foxtv.zone.id/ublive.php?id=391
TVB明珠,http://foxtv.zone.id/ublive.php?id=2437
TVB plus,http://foxtv.zone.id/ublive.php?id=45
TVB plus,http://foxtv.zone.id/ublive.php?id=394
HOY资讯台,http://foxtv.zone.id/ublive.php?id=395
HOY资讯台（備）,http://foxtv.zone.id/ublive.php?id=3268
Viu TV,http://foxtv.zone.id/ublive.php?id=2334
Viutv,http://foxtv.zone.id/ublive.php?id=72
TVB_POPC,http://foxtv.zone.id/ublive.php?id=2818
TVB J2,http://foxtv.zone.id/ublive.php?id=392
TVB J2,http://foxtv.zone.id/ublive.php?id=2834
NOWtv-1,http://foxtv.zone.id/ublive.php?id=396
NOWTV,http://foxtv.zone.id/ublive.php?id=1246
鳳凰香港,http://foxtv.zone.id/ublive.php?id=2810
鳳凰衛視,http://foxtv.zone.id/ublive.php?id=2291
鳳凰衛視,http://foxtv.zone.id/ublive.php?id=2812
鳳凰资讯,http://foxtv.zone.id/ublive.php?id=2811
鳳凰资讯,http://foxtv.zone.id/ublive.php?id=2292
星空衛視,http://foxtv.zone.id/ublive.php?id=56
HOY,http://foxtv.zone.id/ublive.php?id=401
HOY（備）,http://foxtv.zone.id/ublive.php?id=3267
HKIBC,http://foxtv.zone.id/ublive.php?id=354
HKIBC（備）,http://foxtv.zone.id/ublive.php?id=3269
廣東珠江,http://foxtv.zone.id/ublive.php?id=1034
18台,http://foxtv.zone.id/ublive.php?id=44
18台,http://foxtv.zone.id/ublive.php?id=2813
澳門蓮花,http://foxtv.zone.id/ublive.php?id=70
鳳凰電影,http://foxtv.zone.id/ublive.php?id=2814
Viutv 6,http://foxtv.zone.id/ublive.php?id=176
創世電視,http://foxtv.zone.id/ublive.php?id=1317
Euronews English,http://foxtv.zone.id/ublive.php?id=2342
TVB亞洲劇,http://foxtv.zone.id/ublive.php?id=1048
TVB粵語片,http://foxtv.zone.id/ublive.php?id=1589
TVB1,http://foxtv.zone.id/ublive.php?id=1242
TVB DRAMA,http://foxtv.zone.id/ublive.php?id=1243
TVBJ1,http://foxtv.zone.id/ublive.php?id=1244
TVBE,http://foxtv.zone.id/ublive.php?id=1245
新時代東部,http://foxtv.zone.id/ublive.php?id=1286
（時移）新時代東,http://foxtv.zone.id/ublive.php?id=1287
新時代2,http://foxtv.zone.id/ublive.php?id=1288
城市電視,http://foxtv.zone.id/ublive.php?id=1289
新聞頻道,#genre#
HOY资讯台,http://foxtv.zone.id/ublive.php?id=395
HOY资讯台（備）,http://foxtv.zone.id/ublive.php?id=3268
HKIBC,http://foxtv.zone.id/ublive.php?id=354
HKIBC（備）,http://foxtv.zone.id/ublive.php?id=3269
三立新聞,http://foxtv.zone.id/ublive.php?id=43
三立新聞-2,http://foxtv.zone.id/ublive.php?id=2794
三立新聞,http://foxtv.zone.id/ublive.php?id=2392
三立新聞+,http://foxtv.zone.id/ublive.php?id=320
東森新聞,http://foxtv.zone.id/ublive.php?id=1025
東森新聞4,http://foxtv.zone.id/ublive.php?id=2766
東森新聞,http://foxtv.zone.id/ublive.php?id=2393
東森亞洲,http://foxtv.zone.id/ublive.php?id=3
中天新聞,http://foxtv.zone.id/ublive.php?id=2394
中天新聞2,http://foxtv.zone.id/ublive.php?id=2420
中天新聞2台,http://foxtv.zone.id/ublive.php?id=152
民視新聞,http://foxtv.zone.id/ublive.php?id=2395
TVBS新聞,http://foxtv.zone.id/ublive.php?id=2736
TVBS新聞,http://foxtv.zone.id/ublive.php?id=2396
東森財經,http://foxtv.zone.id/ublive.php?id=2397
華視新聞-2,http://foxtv.zone.id/ublive.php?id=2424
三立iNEWS,http://foxtv.zone.id/ublive.php?id=2398
三立iNEWS-2,http://foxtv.zone.id/ublive.php?id=6
台視新聞,http://foxtv.zone.id/ublive.php?id=2399
台視新聞,http://foxtv.zone.id/ublive.php?id=1
中視新聞,http://foxtv.zone.id/ublive.php?id=2400
中視新聞,http://foxtv.zone.id/ublive.php?id=7
寰宇新聞台灣,http://foxtv.zone.id/ublive.php?id=2401
寰宇新聞,http://foxtv.zone.id/ublive.php?id=304
寰宇財經,http://foxtv.zone.id/ublive.php?id=2536
公視新聞,http://foxtv.zone.id/ublive.php?id=20
寰宇臺灣,http://foxtv.zone.id/ublive.php?id=87
年代新聞,http://foxtv.zone.id/ublive.php?id=2719
壹新聞,http://foxtv.zone.id/ublive.php?id=2777
年代新聞-備,http://foxtv.zone.id/ublive.php?id=1099
非凡新聞,http://foxtv.zone.id/ublive.php?id=2795
非凡新聞（備）,http://foxtv.zone.id/ublive.php?id=3236
非凡商業新聞,http://foxtv.zone.id/ublive.php?id=314
台視財經,http://foxtv.zone.id/ublive.php?id=300
運通財經,http://foxtv.zone.id/ublive.php?id=79
SBN全球財經,http://foxtv.zone.id/ublive.php?id=1497
鏡新聞mnews,http://foxtv.zone.id/ublive.php?id=463
三立国際,http://foxtv.zone.id/ublive.php?id=2285
DW德國之聲,http://foxtv.zone.id/ublive.php?id=1059
FRANCE 24 English,http://foxtv.zone.id/ublive.php?id=2231
新唐人亞太台,http://foxtv.zone.id/ublive.php?id=10
CBN News,http://foxtv.zone.id/ublive.php?id=499
Bloomberg Business,http://foxtv.zone.id/ublive.php?id=1046
Al Jazeera,http://foxtv.zone.id/ublive.php?id=1144
Bloomberg Quicktake,http://foxtv.zone.id/ublive.php?id=370
Euronews English,http://foxtv.zone.id/ublive.php?id=2342
NHK WORLD,http://foxtv.zone.id/ublive.php?id=1394
United Nations,http://foxtv.zone.id/ublive.php?id=184
CANAL 24,http://foxtv.zone.id/ublive.php?id=115
Channels,http://foxtv.zone.id/ublive.php?id=1495
CGTN English,http://foxtv.zone.id/ublive.php?id=2362
CGTN Documentary,http://foxtv.zone.id/ublive.php?id=2363
CGTN Français,http://foxtv.zone.id/ublive.php?id=2364
GB News,http://foxtv.zone.id/ublive.php?id=77
FRANCE 24,http://foxtv.zone.id/ublive.php?id=1042
CNN Indonesia,http://foxtv.zone.id/ublive.php?id=1145
影視頻道,#genre#
八大精彩,http://foxtv.zone.id/ublive.php?id=1024
龍華日韓,http://foxtv.zone.id/ublive.php?id=382
東森戲劇,http://foxtv.zone.id/ublive.php?id=2825
東森戲劇-備,http://foxtv.zone.id/ublive.php?id=321
八大戲劇,http://foxtv.zone.id/ublive.php?id=81
緯來戲劇,http://foxtv.zone.id/ublive.php?id=2727
緯來戲劇-備,http://foxtv.zone.id/ublive.php?id=339
東森電影,http://foxtv.zone.id/ublive.php?id=350
東森電影,http://foxtv.zone.id/ublive.php?id=2720
緯來電影,http://foxtv.zone.id/ublive.php?id=2728
緯來電影,http://foxtv.zone.id/ublive.php?id=3252
HBO HD,http://foxtv.zone.id/ublive.php?id=332
HBO HD,http://foxtv.zone.id/ublive.php?id=2823
東森洋片,http://foxtv.zone.id/ublive.php?id=1128
壹電影,http://foxtv.zone.id/ublive.php?id=2284
好萊塢電影,http://foxtv.zone.id/ublive.php?id=37
愛爾達影劇,http://foxtv.zone.id/ublive.php?id=500
CineMAX,http://foxtv.zone.id/ublive.php?id=346
緯來精彩,http://foxtv.zone.id/ublive.php?id=2280
EYE戲劇,http://foxtv.zone.id/ublive.php?id=191
三立戲劇,http://foxtv.zone.id/ublive.php?id=64
三立戲劇,http://foxtv.zone.id/ublive.php?id=2819
龍華偶像,http://foxtv.zone.id/ublive.php?id=385
霹靂臺灣,http://foxtv.zone.id/ublive.php?id=1339
美亞電影,http://foxtv.zone.id/ublive.php?id=375
AMC,http://foxtv.zone.id/ublive.php?id=84
HBOSignature,http://foxtv.zone.id/ublive.php?id=329
HBOSignature,http://foxtv.zone.id/ublive.php?id=2824
HBO Hits,http://foxtv.zone.id/ublive.php?id=330
采昌影劇,http://foxtv.zone.id/ublive.php?id=2804
影迷數位電影,http://foxtv.zone.id/ublive.php?id=2800
龍華戲劇,http://foxtv.zone.id/ublive.php?id=2796
龍華經典,http://foxtv.zone.id/ublive.php?id=100
龍翔時代,http://foxtv.zone.id/ublive.php?id=373
AXN臺灣,http://foxtv.zone.id/ublive.php?id=2816
天映經典,http://foxtv.zone.id/ublive.php?id=2289
AXN亞洲,http://foxtv.zone.id/ublive.php?id=1066
Trill恐怖電影,http://foxtv.zone.id/ublive.php?id=18
龍華電影,http://foxtv.zone.id/ublive.php?id=311
華納電影,http://foxtv.zone.id/ublive.php?id=83
甄嬛传,http://foxtv.zone.id/ublive.php?id=1060
CATCHPLAY,http://foxtv.zone.id/ublive.php?id=362
TVB亞洲劇,http://foxtv.zone.id/ublive.php?id=1048
TVB粵語片,http://foxtv.zone.id/ublive.php?id=1589
CHC高清電影,http://foxtv.zone.id/ublive.php?id=1345
CHC動作電影,http://foxtv.zone.id/ublive.php?id=1346
CHC家庭影院,http://foxtv.zone.id/ublive.php?id=1347
CBN歡笑劇場4K,http://foxtv.zone.id/ublive.php?id=1348
SETONE,http://foxtv.zone.id/ublive.php?id=1349
龍華洋片,http://foxtv.zone.id/ublive.php?id=341
飢餓遊戲,http://foxtv.zone.id/ublive.php?id=264
台視時光機,http://foxtv.zone.id/ublive.php?id=2555
龍翔時代,http://foxtv.zone.id/ublive.php?id=1175
體育頻道,#genre#
緯來體育,http://foxtv.zone.id/ublive.php?id=118
緯來體育,http://foxtv.zone.id/ublive.php?id=2732
ELTA體育1,http://foxtv.zone.id/ublive.php?id=192
ELTA體育1,http://foxtv.zone.id/ublive.php?id=2729
ELTA體育2,http://foxtv.zone.id/ublive.php?id=2730
ELTA體育2,http://foxtv.zone.id/ublive.php?id=193
ELTA體育3,http://foxtv.zone.id/ublive.php?id=2731
ELTA體育3,http://foxtv.zone.id/ublive.php?id=194
ELTA體育4,http://foxtv.zone.id/ublive.php?id=2820
ELTA體育4-備,http://foxtv.zone.id/ublive.php?id=3255
FOX Sport 1,http://foxtv.zone.id/ublive.php?id=2791
FOX Sport 2,http://foxtv.zone.id/ublive.php?id=1132
Eleven Sport 1,http://foxtv.zone.id/ublive.php?id=3224
Eleven Sport 2,http://foxtv.zone.id/ublive.php?id=301
Z頻道,http://foxtv.zone.id/ublive.php?id=1130
博斯無限,http://foxtv.zone.id/ublive.php?id=381
博斯無限,http://foxtv.zone.id/ublive.php?id=2797
博斯無限2,http://foxtv.zone.id/ublive.php?id=426
博斯無限2,http://foxtv.zone.id/ublive.php?id=2798
博斯網球,http://foxtv.zone.id/ublive.php?id=498
博斯高球1,http://foxtv.zone.id/ublive.php?id=377
博斯高球2,http://foxtv.zone.id/ublive.php?id=378
博斯魅力,http://foxtv.zone.id/ublive.php?id=175
博斯運動1,http://foxtv.zone.id/ublive.php?id=379
博斯運動2,http://foxtv.zone.id/ublive.php?id=380
歐洲體育,http://foxtv.zone.id/ublive.php?id=1342
魅力足球,http://foxtv.zone.id/ublive.php?id=464
J SPORTS 1,http://foxtv.zone.id/ublive.php?id=129
J SPORTS 2,http://foxtv.zone.id/ublive.php?id=130
J SPORTS 3,http://foxtv.zone.id/ublive.php?id=131
J SPORTS 4,http://foxtv.zone.id/ublive.php?id=132
mlb  network,http://foxtv.zone.id/ublive.php?id=3250
BTN,http://foxtv.zone.id/ublive.php?id=3256
mlb  network,http://foxtv.zone.id/ublive.php?id=3251
bt espn hd,http://foxtv.zone.id/ublive.php?id=2790
ESPN 1,http://foxtv.zone.id/ublive.php?id=1182
ESPN 1,http://foxtv.zone.id/ublive.php?id=2788
ESPN 2,http://foxtv.zone.id/ublive.php?id=2789
NBA,http://foxtv.zone.id/ublive.php?id=2792
NBA TV US,http://foxtv.zone.id/ublive.php?id=1185
Fox Sport 2,http://foxtv.zone.id/ublive.php?id=1187
TSN 1,http://foxtv.zone.id/ublive.php?id=1273
TSN 2,http://foxtv.zone.id/ublive.php?id=1274
TSN 3,http://foxtv.zone.id/ublive.php?id=1275
TSN 4,http://foxtv.zone.id/ublive.php?id=1276
TSN 5,http://foxtv.zone.id/ublive.php?id=1277
SportNet ON,http://foxtv.zone.id/ublive.php?id=1278
SportNet One,http://foxtv.zone.id/ublive.php?id=1279
SportNet World,http://foxtv.zone.id/ublive.php?id=1280
SportNet 360,http://foxtv.zone.id/ublive.php?id=1281
NBA CA,http://foxtv.zone.id/ublive.php?id=1282
Freesports,http://foxtv.zone.id/ublive.php?id=1412
BT Sport 2,http://foxtv.zone.id/ublive.php?id=166
BT Sport 3,http://foxtv.zone.id/ublive.php?id=167
BT Sport 1,http://foxtv.zone.id/ublive.php?id=165
Sky Sports 1,http://foxtv.zone.id/ublive.php?id=172
Sky Sport 2,http://foxtv.zone.id/ublive.php?id=171
Sky Sport 3,http://foxtv.zone.id/ublive.php?id=183
Sky Sport 5,http://foxtv.zone.id/ublive.php?id=418
sky sports racing hd,http://foxtv.zone.id/ublive.php?id=2778
sky news hd,http://foxtv.zone.id/ublive.php?id=2779
UK Euro Sport 1,http://foxtv.zone.id/ublive.php?id=3226
UK Euro Sport 2,http://foxtv.zone.id/ublive.php?id=3227
sky sports mix,http://foxtv.zone.id/ublive.php?id=2780
sky sports arena,http://foxtv.zone.id/ublive.php?id=2781
sky sports football,http://foxtv.zone.id/ublive.php?id=2782
sky sports premier league,http://foxtv.zone.id/ublive.php?id=2783
sky sports the open,http://foxtv.zone.id/ublive.php?id=2784
sky sports action,http://foxtv.zone.id/ublive.php?id=2785
sky sports main event,http://foxtv.zone.id/ublive.php?id=2787
sky sports f1,http://foxtv.zone.id/ublive.php?id=3237
Sky Sports F1,http://foxtv.zone.id/ublive.php?id=182
cbs action,http://foxtv.zone.id/ublive.php?id=3238
Russia Today,http://foxtv.zone.id/ublive.php?id=3239
4seven hd,http://foxtv.zone.id/ublive.php?id=3240
racing uk hd,http://foxtv.zone.id/ublive.php?id=3241
sky greats,http://foxtv.zone.id/ublive.php?id=3243
channel 4 hd,http://foxtv.zone.id/ublive.php?id=3245
channel 5,http://foxtv.zone.id/ublive.php?id=3247
sony tv,http://foxtv.zone.id/ublive.php?id=3248
SKY SPORT NBA,http://foxtv.zone.id/ublive.php?id=2738
SKY SPORT ARENA,http://foxtv.zone.id/ublive.php?id=2739
SKY F1,http://foxtv.zone.id/ublive.php?id=2740
Sky sport uno,http://foxtv.zone.id/ublive.php?id=1597
Rai Sport,http://foxtv.zone.id/ublive.php?id=1613
NBA 2TV,http://foxtv.zone.id/ublive.php?id=3044
Sport TV 2,http://foxtv.zone.id/ublive.php?id=1785
紀實頻道,#genre#
亞洲旅遊,http://foxtv.zone.id/ublive.php?id=2299
探索頻道,http://foxtv.zone.id/ublive.php?id=2817
探索頻道,http://foxtv.zone.id/ublive.php?id=1035
大陸尋奇,http://foxtv.zone.id/ublive.php?id=102
動物星球,http://foxtv.zone.id/ublive.php?id=367
探索亞洲,http://foxtv.zone.id/ublive.php?id=306
探索科學,http://foxtv.zone.id/ublive.php?id=343
探索科學-2,http://foxtv.zone.id/ublive.php?id=3275
Nat Geo WILD,http://foxtv.zone.id/ublive.php?id=388
國家野生（英）,http://foxtv.zone.id/ublive.php?id=1038
CI罪案偵查,http://foxtv.zone.id/ublive.php?id=2303
探索EVE,http://foxtv.zone.id/ublive.php?id=1036
視納華仁紀實,http://foxtv.zone.id/ublive.php?id=91
美食星球,http://foxtv.zone.id/ublive.php?id=3073
美食星球,http://foxtv.zone.id/ublive.php?id=1360
EYE旅遊,http://foxtv.zone.id/ublive.php?id=1494
探索動力DMAX,http://foxtv.zone.id/ublive.php?id=335
Globetrotter（MOD）,http://foxtv.zone.id/ublive.php?id=3259
NASA Live,http://foxtv.zone.id/ublive.php?id=196
TV5MONDE STYLE,http://foxtv.zone.id/ublive.php?id=389
動物世界,http://foxtv.zone.id/ublive.php?id=291
法國時裝,http://foxtv.zone.id/ublive.php?id=2287
台灣啟示錄,http://foxtv.zone.id/ublive.php?id=2765
CCTV17,http://foxtv.zone.id/ublive.php?id=3260
TLC,http://foxtv.zone.id/ublive.php?id=1533
TLC Canada,http://foxtv.zone.id/ublive.php?id=1262
Food Network Canada,http://foxtv.zone.id/ublive.php?id=1265
History,http://foxtv.zone.id/ublive.php?id=1413
少兒頻道,#genre#
Bebefinn,http://foxtv.zone.id/ublive.php?id=489
Leigha Marina,http://foxtv.zone.id/ublive.php?id=313
MOMO親子,http://foxtv.zone.id/ublive.php?id=2767
東森幼幼,http://foxtv.zone.id/ublive.php?id=371
東森幼幼,http://foxtv.zone.id/ublive.php?id=2771
東森亞洲呦呦,http://foxtv.zone.id/ublive.php?id=293
CN Asia,http://foxtv.zone.id/ublive.php?id=2768
Nick Jr.,http://foxtv.zone.id/ublive.php?id=50
Mickey Mouse,http://foxtv.zone.id/ublive.php?id=460
PAW Patrol,http://foxtv.zone.id/ublive.php?id=2226
Dreamworks,http://foxtv.zone.id/ublive.php?id=48
CN卡通,http://foxtv.zone.id/ublive.php?id=107
Tom and Jerry,http://foxtv.zone.id/ublive.php?id=3209
Curious George,http://foxtv.zone.id/ublive.php?id=173
Animax,http://foxtv.zone.id/ublive.php?id=59
靖天卡通,http://foxtv.zone.id/ublive.php?id=344
Treehouse,http://foxtv.zone.id/ublive.php?id=55
Nickj,http://foxtv.zone.id/ublive.php?id=53
Disney,http://foxtv.zone.id/ublive.php?id=5
Boomerang,http://foxtv.zone.id/ublive.php?id=57
Hogi,http://foxtv.zone.id/ublive.php?id=2346
BABY LOONEY TUNES,http://foxtv.zone.id/ublive.php?id=2438
Beep Beep,http://foxtv.zone.id/ublive.php?id=3015
Baby songs,http://foxtv.zone.id/ublive.php?id=3018
Minnie Bow-Toons,http://foxtv.zone.id/ublive.php?id=456
Pixar Cars,http://foxtv.zone.id/ublive.php?id=1562
CCTV14,http://foxtv.zone.id/ublive.php?id=214
CCTV14,http://foxtv.zone.id/ublive.php?id=2826
音樂宗教,#genre#
好消息,http://foxtv.zone.id/ublive.php?id=104
好消息2,http://foxtv.zone.id/ublive.php?id=363
Gentle Music,http://foxtv.zone.id/ublive.php?id=58
Water Sounds,http://foxtv.zone.id/ublive.php?id=496
Hits Radio,http://foxtv.zone.id/ublive.php?id=4
Unbelievable Beauty,http://foxtv.zone.id/ublive.php?id=1002
Relaxing Music,http://foxtv.zone.id/ublive.php?id=151
Relaxing Jazz Piano,http://foxtv.zone.id/ublive.php?id=1351
流行鋼琴曲,http://foxtv.zone.id/ublive.php?id=1361
Mezzo Live,http://foxtv.zone.id/ublive.php?id=60
Lofi Hip Hop,http://foxtv.zone.id/ublive.php?id=2350
4K Nature,http://foxtv.zone.id/ublive.php?id=1015
Coffee Jazz,http://foxtv.zone.id/ublive.php?id=1019
Space Ambient,http://foxtv.zone.id/ublive.php?id=1005
Rolling Cam Venice,http://foxtv.zone.id/ublive.php?id=1007
大愛一臺,http://foxtv.zone.id/ublive.php?id=11
大愛二臺,http://foxtv.zone.id/ublive.php?id=197
Baroque Live Music,http://foxtv.zone.id/ublive.php?id=1027
唯心電視,http://foxtv.zone.id/ublive.php?id=1150
人間衛視,http://foxtv.zone.id/ublive.php?id=101
Good Life Radio,http://foxtv.zone.id/ublive.php?id=1152
Rainy Jazz,http://foxtv.zone.id/ublive.php?id=1089
Tropical House Radio,http://foxtv.zone.id/ublive.php?id=1090
Sleeping Music,http://foxtv.zone.id/ublive.php?id=1087
Relaxing Piano Collection,http://foxtv.zone.id/ublive.php?id=1088
佛衛慈悲台,http://foxtv.zone.id/ublive.php?id=1306
生命電視,http://foxtv.zone.id/ublive.php?id=1124
華藏電視,http://foxtv.zone.id/ublive.php?id=1053
治愈音樂,http://foxtv.zone.id/ublive.php?id=1503
正德電視,http://foxtv.zone.id/ublive.php?id=42
SupremeMasterTV,http://foxtv.zone.id/ublive.php?id=323
鳥鳴音樂,http://foxtv.zone.id/ublive.php?id=1407
GRASS COTTON,http://foxtv.zone.id/ublive.php?id=3221
Heavenly Harp Music,http://foxtv.zone.id/ublive.php?id=2540
大陸頻道,#genre#
CGTN English,http://foxtv.zone.id/ublive.php?id=2362
CGTN Documentary,http://foxtv.zone.id/ublive.php?id=2363
CGTN Français,http://foxtv.zone.id/ublive.php?id=2364
CCTV1,http://foxtv.zone.id/ublive.php?id=2305
CCTV1,http://foxtv.zone.id/ublive.php?id=200
CCTV2,http://foxtv.zone.id/ublive.php?id=201
CCTV2,http://foxtv.zone.id/ublive.php?id=2763
CCTV3,http://foxtv.zone.id/ublive.php?id=202
CCTV3,http://foxtv.zone.id/ublive.php?id=2808
CCTV4,http://foxtv.zone.id/ublive.php?id=248
CCTV4,http://foxtv.zone.id/ublive.php?id=203
CCTV4,http://foxtv.zone.id/ublive.php?id=2764
CCTV5,http://foxtv.zone.id/ublive.php?id=204
CCTV5plus,http://foxtv.zone.id/ublive.php?id=205
CCTV5,http://foxtv.zone.id/ublive.php?id=2760
CCTV5plus,http://foxtv.zone.id/ublive.php?id=2759
CCTV6,http://foxtv.zone.id/ublive.php?id=206
CCTV6,http://foxtv.zone.id/ublive.php?id=2758
CCTV7,http://foxtv.zone.id/ublive.php?id=207
CCTV7,http://foxtv.zone.id/ublive.php?id=2757
CCTV8,http://foxtv.zone.id/ublive.php?id=208
CCTV8,http://foxtv.zone.id/ublive.php?id=2756
CCTV9,http://foxtv.zone.id/ublive.php?id=2308
CCTV9,http://foxtv.zone.id/ublive.php?id=209
CCTV10,http://foxtv.zone.id/ublive.php?id=210
CCTV11,http://foxtv.zone.id/ublive.php?id=2809
CCTV11,http://foxtv.zone.id/ublive.php?id=211
CCTV12,http://foxtv.zone.id/ublive.php?id=212
CCTV12,http://foxtv.zone.id/ublive.php?id=2755
CCTV13,http://foxtv.zone.id/ublive.php?id=213
CCTV13,http://foxtv.zone.id/ublive.php?id=2754
CCTV14,http://foxtv.zone.id/ublive.php?id=214
CCTV14,http://foxtv.zone.id/ublive.php?id=2826
CCTV15,http://foxtv.zone.id/ublive.php?id=215
CCTV16,http://foxtv.zone.id/ublive.php?id=2821
CCTV17,http://foxtv.zone.id/ublive.php?id=3260
浙江卫视,http://foxtv.zone.id/ublive.php?id=217
江苏卫视,http://foxtv.zone.id/ublive.php?id=218
江苏卫视,http://foxtv.zone.id/ublive.php?id=2829
北京卫视,http://foxtv.zone.id/ublive.php?id=220
北京衛視,http://foxtv.zone.id/ublive.php?id=221
广东卫视,http://foxtv.zone.id/ublive.php?id=231
广东卫视,http://foxtv.zone.id/ublive.php?id=1499
东方卫视,http://foxtv.zone.id/ublive.php?id=224
河南卫视,http://foxtv.zone.id/ublive.php?id=225
湖南卫视,http://foxtv.zone.id/ublive.php?id=3228
湖南卫视,http://foxtv.zone.id/ublive.php?id=226
湖北卫视,http://foxtv.zone.id/ublive.php?id=3229
湖北卫视,http://foxtv.zone.id/ublive.php?id=227
东南卫视,http://foxtv.zone.id/ublive.php?id=228
辽宁卫视,http://foxtv.zone.id/ublive.php?id=229
深圳卫视,http://foxtv.zone.id/ublive.php?id=230
深圳卫视,http://foxtv.zone.id/ublive.php?id=3230
安徽卫视,http://foxtv.zone.id/ublive.php?id=232
安徽卫视,http://foxtv.zone.id/ublive.php?id=2830
四川卫视,http://foxtv.zone.id/ublive.php?id=233
山东卫视,http://foxtv.zone.id/ublive.php?id=234
青田電視台,http://foxtv.zone.id/ublive.php?id=2295
天津衛視,http://foxtv.zone.id/ublive.php?id=1093
江西衛視,http://foxtv.zone.id/ublive.php?id=1097
新疆衛視,http://foxtv.zone.id/ublive.php?id=1026
にっぽん,#genre#
JapaNews24,http://foxtv.zone.id/ublive.php?id=425
スカイA,http://foxtv.zone.id/ublive.php?id=2433
フジone,http://foxtv.zone.id/ublive.php?id=2300
フジ two,http://foxtv.zone.id/ublive.php?id=2301
フジ next,http://foxtv.zone.id/ublive.php?id=2750
KANSAI News24,http://foxtv.zone.id/ublive.php?id=247
メ～テレNEWS,http://foxtv.zone.id/ublive.php?id=245
広島ニュース,http://foxtv.zone.id/ublive.php?id=1095
TBS NEWS,http://foxtv.zone.id/ublive.php?id=1096
RKB NEWS 24,http://foxtv.zone.id/ublive.php?id=1043
STV NEWS,http://foxtv.zone.id/ublive.php?id=1500
テレ朝チャンネル1,http://foxtv.zone.id/ublive.php?id=2271
テレ朝チャンネル2,http://foxtv.zone.id/ublive.php?id=2344
スポーツライブ＋,http://foxtv.zone.id/ublive.php?id=2343
読売テレビ,http://foxtv.zone.id/ublive.php?id=198
関西テレビ,http://foxtv.zone.id/ublive.php?id=235
BS日テレ,http://foxtv.zone.id/ublive.php?id=240
BS朝日,http://foxtv.zone.id/ublive.php?id=241
BS-TBS,http://foxtv.zone.id/ublive.php?id=3214
BS-TBS,http://foxtv.zone.id/ublive.php?id=242
BSテレビ東京,http://foxtv.zone.id/ublive.php?id=243
BSフジ,http://foxtv.zone.id/ublive.php?id=244
旅チャンネル,http://foxtv.zone.id/ublive.php?id=2304
TOKYO MX 1,http://foxtv.zone.id/ublive.php?id=2204
TOKYO MX 2,http://foxtv.zone.id/ublive.php?id=2205
朝日放送テレビ,http://foxtv.zone.id/ublive.php?id=237
時代劇専門チャンネル,http://foxtv.zone.id/ublive.php?id=287
TV Tokyo,http://foxtv.zone.id/ublive.php?id=123
J SPORTS 1,http://foxtv.zone.id/ublive.php?id=129
JSPORTS 1,http://foxtv.zone.id/ublive.php?id=1210
J SPORTS 2,http://foxtv.zone.id/ublive.php?id=130
J SPORTS 3,http://foxtv.zone.id/ublive.php?id=131
J SPORTS 4,http://foxtv.zone.id/ublive.php?id=132
ABC朝日,http://foxtv.zone.id/ublive.php?id=127
FU JI,http://foxtv.zone.id/ublive.php?id=122
テレビ東京,http://foxtv.zone.id/ublive.php?id=2202
フジテレビ,http://foxtv.zone.id/ublive.php?id=2203
テレビ朝日,http://foxtv.zone.id/ublive.php?id=125
大阪TV,http://foxtv.zone.id/ublive.php?id=126
WOWOWプライム,http://foxtv.zone.id/ublive.php?id=133
WOWOWライブ,http://foxtv.zone.id/ublive.php?id=134
WOWOWシネマ,http://foxtv.zone.id/ublive.php?id=135
スターチャンネル1,http://foxtv.zone.id/ublive.php?id=136
日本テレビ,http://foxtv.zone.id/ublive.php?id=119
毎日放送,http://foxtv.zone.id/ublive.php?id=199
ゴルフネットワーク,http://foxtv.zone.id/ublive.php?id=249
HTB北海道,http://foxtv.zone.id/ublive.php?id=39
日テレG+,http://foxtv.zone.id/ublive.php?id=2298
GAORA SPORTS,http://foxtv.zone.id/ublive.php?id=296
TBS,http://foxtv.zone.id/ublive.php?id=124
TBS,http://foxtv.zone.id/ublive.php?id=2201
アニマックス,http://foxtv.zone.id/ublive.php?id=139
グリーンチャンネル,http://foxtv.zone.id/ublive.php?id=140
キッズステーション,http://foxtv.zone.id/ublive.php?id=289
QVCライブ,http://foxtv.zone.id/ublive.php?id=2218
BS日本映画専門Ch,http://foxtv.zone.id/ublive.php?id=2219
Discovery Japan,http://foxtv.zone.id/ublive.php?id=290
衛星劇場,http://foxtv.zone.id/ublive.php?id=2345
日テレG＋,http://foxtv.zone.id/ublive.php?id=2434
兵庫県の最新,http://foxtv.zone.id/ublive.php?id=1142
KBC NEWS,http://foxtv.zone.id/ublive.php?id=3219
TBS,http://foxtv.zone.id/ublive.php?id=2917
BS-富士,http://foxtv.zone.id/ublive.php?id=2919
フジテレビ富士,http://foxtv.zone.id/ublive.php?id=2920
テレビ朝日,http://foxtv.zone.id/ublive.php?id=2921
テレビ東京,http://foxtv.zone.id/ublive.php?id=2922
日本テレビ,http://foxtv.zone.id/ublive.php?id=2923
BS朝日,http://foxtv.zone.id/ublive.php?id=3213
BS日テレ,http://foxtv.zone.id/ublive.php?id=1215
한국,#genre#
KBS KOREA,http://foxtv.zone.id/ublive.php?id=1040
연합뉴스TV,http://foxtv.zone.id/ublive.php?id=1039
YTN2,http://foxtv.zone.id/ublive.php?id=1058
KBS1,http://foxtv.zone.id/ublive.php?id=2752
KBS2,http://foxtv.zone.id/ublive.php?id=2753
CATCH ON2,http://foxtv.zone.id/ublive.php?id=3200
SBS,http://foxtv.zone.id/ublive.php?id=252
SBS,http://foxtv.zone.id/ublive.php?id=3107
SBS BIZ,http://foxtv.zone.id/ublive.php?id=3201
NOW[미드],http://foxtv.zone.id/ublive.php?id=3166
AXN[미드],http://foxtv.zone.id/ublive.php?id=3168
SCREEN,http://foxtv.zone.id/ublive.php?id=3153
런닝맨,http://foxtv.zone.id/ublive.php?id=2347
KBS드라마1,http://foxtv.zone.id/ublive.php?id=2348
I.NET,http://foxtv.zone.id/ublive.php?id=2351
SkySports,http://foxtv.zone.id/ublive.php?id=2352
KBSN Sports,http://foxtv.zone.id/ublive.php?id=2353
SBS Sports,http://foxtv.zone.id/ublive.php?id=2354
FTV,http://foxtv.zone.id/ublive.php?id=2355
바둑TV,http://foxtv.zone.id/ublive.php?id=2356
FTV,http://foxtv.zone.id/ublive.php?id=2905
OCN Thrills,http://foxtv.zone.id/ublive.php?id=2357
OBS,http://foxtv.zone.id/ublive.php?id=2358
투니버스Tooniverse 39,http://foxtv.zone.id/ublive.php?id=2360
연변위성,http://foxtv.zone.id/ublive.php?id=2361
TVN,http://foxtv.zone.id/ublive.php?id=295
MBC,http://foxtv.zone.id/ublive.php?id=251
MBC,http://foxtv.zone.id/ublive.php?id=3106
MBN,http://foxtv.zone.id/ublive.php?id=257
Mnet,http://foxtv.zone.id/ublive.php?id=3203
MBN,http://foxtv.zone.id/ublive.php?id=3197
MBC스포츠,http://foxtv.zone.id/ublive.php?id=265
JTBC골프,http://foxtv.zone.id/ublive.php?id=268
JTBC,http://foxtv.zone.id/ublive.php?id=3108
JTBC,http://foxtv.zone.id/ublive.php?id=253
tvN,http://foxtv.zone.id/ublive.php?id=1154
OCN,http://foxtv.zone.id/ublive.php?id=488
OCN Movies,http://foxtv.zone.id/ublive.php?id=3165
iNet,http://foxtv.zone.id/ublive.php?id=490
OCN,http://foxtv.zone.id/ublive.php?id=3206
Spotv,http://foxtv.zone.id/ublive.php?id=266
SPOTV ON1,http://foxtv.zone.id/ublive.php?id=3104
Spotv2,http://foxtv.zone.id/ublive.php?id=267
SPOTV ON2,http://foxtv.zone.id/ublive.php?id=3105
THE K-POP,http://foxtv.zone.id/ublive.php?id=493
SBS골프,http://foxtv.zone.id/ublive.php?id=486
TV Chosun,http://foxtv.zone.id/ublive.php?id=3109
한국경제,http://foxtv.zone.id/ublive.php?id=1064
매일경제TV,http://foxtv.zone.id/ublive.php?id=1065
YTN 사이언스,http://foxtv.zone.id/ublive.php?id=1605
Arirang TV,http://foxtv.zone.id/ublive.php?id=256
Mnet,http://foxtv.zone.id/ublive.php?id=1136
MBCevery1,http://foxtv.zone.id/ublive.php?id=476
Tconvers,http://foxtv.zone.id/ublive.php?id=1134
KBC,http://foxtv.zone.id/ublive.php?id=1307
MTN,http://foxtv.zone.id/ublive.php?id=1504
토마토TV,http://foxtv.zone.id/ublive.php?id=1544
이데일리TV,http://foxtv.zone.id/ublive.php?id=1554
EBS1,http://foxtv.zone.id/ublive.php?id=2439
EBS2,http://foxtv.zone.id/ublive.php?id=3006
EBS KIDS,http://foxtv.zone.id/ublive.php?id=3007
EBS PLUS1,http://foxtv.zone.id/ublive.php?id=3008
EBS PLUS2,http://foxtv.zone.id/ublive.php?id=3009
EBSe,http://foxtv.zone.id/ublive.php?id=3010
tvN Show,http://foxtv.zone.id/ublive.php?id=1020
tvN Story,http://foxtv.zone.id/ublive.php?id=1062
Inet TV,http://foxtv.zone.id/ublive.php?id=263
Channel A,http://foxtv.zone.id/ublive.php?id=258
Tooniverse,http://foxtv.zone.id/ublive.php?id=1100
대교 어린이,http://foxtv.zone.id/ublive.php?id=260
CNTV,http://foxtv.zone.id/ublive.php?id=3167
Kids Talk Talk,http://foxtv.zone.id/ublive.php?id=1582
SPOTV Golf,http://foxtv.zone.id/ublive.php?id=3169
JEI재능TV,http://foxtv.zone.id/ublive.php?id=3205
Channel A,http://foxtv.zone.id/ublive.php?id=3204
CATCH ON1,http://foxtv.zone.id/ublive.php?id=3207
TV Chosun 2,http://foxtv.zone.id/ublive.php?id=3202
SBS Golf,http://foxtv.zone.id/ublive.php?id=3170
JTBC Golf,http://foxtv.zone.id/ublive.php?id=3173
JTBC Golf&Sports,http://foxtv.zone.id/ublive.php?id=3198
MBC Sports,http://foxtv.zone.id/ublive.php?id=3174
SBS Sports,http://foxtv.zone.id/ublive.php?id=3199
SPOTV2,http://foxtv.zone.id/ublive.php?id=250
KBSN Sports,http://foxtv.zone.id/ublive.php?id=174
TVBaduk,http://foxtv.zone.id/ublive.php?id=2906
Channel China,http://foxtv.zone.id/ublive.php?id=2907
SKY Sports,http://foxtv.zone.id/ublive.php?id=2910
tvN Sports,http://foxtv.zone.id/ublive.php?id=2931
Smithsonian,http://foxtv.zone.id/ublive.php?id=2934
BTN,http://foxtv.zone.id/ublive.php?id=3078
SPOTV,http://foxtv.zone.id/ublive.php?id=3080
CHING,http://foxtv.zone.id/ublive.php?id=3081
CPBC,http://foxtv.zone.id/ublive.php?id=3083
CTS,http://foxtv.zone.id/ublive.php?id=3084
KBS2,http://foxtv.zone.id/ublive.php?id=3075
CGNTV GW,http://foxtv.zone.id/ublive.php?id=2911
Discovery,http://foxtv.zone.id/ublive.php?id=3196
美國頻道,#genre#
FOX NOW,http://foxtv.zone.id/ublive.php?id=1506
mlb  network,http://foxtv.zone.id/ublive.php?id=3250
BTN,http://foxtv.zone.id/ublive.php?id=3256
mlb  network,http://foxtv.zone.id/ublive.php?id=3251
TLC,http://foxtv.zone.id/ublive.php?id=1206
FOX,http://foxtv.zone.id/ublive.php?id=1218
bloomberg,http://foxtv.zone.id/ublive.php?id=3232
WillowCricket,http://foxtv.zone.id/ublive.php?id=3231
coking chan,http://foxtv.zone.id/ublive.php?id=3233
CNN,http://foxtv.zone.id/ublive.php?id=1507
CNN （備用）,http://foxtv.zone.id/ublive.php?id=1102
MSNBC（備）,http://foxtv.zone.id/ublive.php?id=1104
ABC News,http://foxtv.zone.id/ublive.php?id=1508
NBC,http://foxtv.zone.id/ublive.php?id=1509
NBC,http://foxtv.zone.id/ublive.php?id=1217
Fox Business,http://foxtv.zone.id/ublive.php?id=1511
Fox Business,http://foxtv.zone.id/ublive.php?id=1108
FOX Weather,http://foxtv.zone.id/ublive.php?id=2742
E!,http://foxtv.zone.id/ublive.php?id=1222
E,http://foxtv.zone.id/ublive.php?id=1536
Hbo East,http://foxtv.zone.id/ublive.php?id=1513
HBO Family,http://foxtv.zone.id/ublive.php?id=1113
HBO Comedy,http://foxtv.zone.id/ublive.php?id=1109
Hbo Family,http://foxtv.zone.id/ublive.php?id=1512
HBO Signature,http://foxtv.zone.id/ublive.php?id=1112
HBO 2 US,http://foxtv.zone.id/ublive.php?id=1111
Hbo One,http://foxtv.zone.id/ublive.php?id=1514
HBO 1 US,http://foxtv.zone.id/ublive.php?id=1110
Tennis chan,http://foxtv.zone.id/ublive.php?id=1519
Tennis chan（備）,http://foxtv.zone.id/ublive.php?id=3235
law and crime,http://foxtv.zone.id/ublive.php?id=1540
TBS,http://foxtv.zone.id/ublive.php?id=1545
MTV,http://foxtv.zone.id/ublive.php?id=1546
FX,http://foxtv.zone.id/ublive.php?id=1551
Lifetime,http://foxtv.zone.id/ublive.php?id=1553
CNBC,http://foxtv.zone.id/ublive.php?id=1106
CNBC,http://foxtv.zone.id/ublive.php?id=1555
CW,http://foxtv.zone.id/ublive.php?id=1557
CW,http://foxtv.zone.id/ublive.php?id=1220
Animal,http://foxtv.zone.id/ublive.php?id=1558
Animal Planet,http://foxtv.zone.id/ublive.php?id=1203
AE,http://foxtv.zone.id/ublive.php?id=1559
Investigation Discovery,http://foxtv.zone.id/ublive.php?id=1564
Lifetime Movie Network,http://foxtv.zone.id/ublive.php?id=1565
Showtime,http://foxtv.zone.id/ublive.php?id=1568
StarZ,http://foxtv.zone.id/ublive.php?id=1569
USA Network,http://foxtv.zone.id/ublive.php?id=1571
Right Now,http://foxtv.zone.id/ublive.php?id=144
Atlanta,http://foxtv.zone.id/ublive.php?id=1055
Panama City,http://foxtv.zone.id/ublive.php?id=1056
Pawleys Island,http://foxtv.zone.id/ublive.php?id=1057
HGTV,http://foxtv.zone.id/ublive.php?id=1538
HGTV,http://foxtv.zone.id/ublive.php?id=2311
National Geographic,http://foxtv.zone.id/ublive.php?id=2312
Nat Geo Wild,http://foxtv.zone.id/ublive.php?id=1521
Nat Geo Wild,http://foxtv.zone.id/ublive.php?id=2313
Cinemax,http://foxtv.zone.id/ublive.php?id=2314
IFC,http://foxtv.zone.id/ublive.php?id=1362
ESPN NEWS,http://foxtv.zone.id/ublive.php?id=1363
CBS Sport,http://foxtv.zone.id/ublive.php?id=1364
Fight Box,http://foxtv.zone.id/ublive.php?id=1365
WABC,http://foxtv.zone.id/ublive.php?id=3264
Outdoor,http://foxtv.zone.id/ublive.php?id=1368
SEC Network,http://foxtv.zone.id/ublive.php?id=1369
PBS Kids,http://foxtv.zone.id/ublive.php?id=1370
WGN,http://foxtv.zone.id/ublive.php?id=1372
FX,http://foxtv.zone.id/ublive.php?id=1373
Fuse,http://foxtv.zone.id/ublive.php?id=1376
FX Movie,http://foxtv.zone.id/ublive.php?id=1380
Comet,http://foxtv.zone.id/ublive.php?id=1381
5 Star Max,http://foxtv.zone.id/ublive.php?id=1174
龍翔時代,http://foxtv.zone.id/ublive.php?id=1175
MoreMax,http://foxtv.zone.id/ublive.php?id=1176
Hallmark Movie,http://foxtv.zone.id/ublive.php?id=1179
TCM,http://foxtv.zone.id/ublive.php?id=1180
Starz in Black,http://foxtv.zone.id/ublive.php?id=1181
ESPN 1,http://foxtv.zone.id/ublive.php?id=1182
ESPN 1,http://foxtv.zone.id/ublive.php?id=2788
ESPN 2,http://foxtv.zone.id/ublive.php?id=2789
NBA,http://foxtv.zone.id/ublive.php?id=2792
NBA TV US,http://foxtv.zone.id/ublive.php?id=1185
Fight network,http://foxtv.zone.id/ublive.php?id=1527
Fox Sport 2,http://foxtv.zone.id/ublive.php?id=1187
NFL Network,http://foxtv.zone.id/ublive.php?id=1189
Food network 美,http://foxtv.zone.id/ublive.php?id=1526
Cartoon Network US,http://foxtv.zone.id/ublive.php?id=1211
USA Network,http://foxtv.zone.id/ublive.php?id=1230
Diy network,http://foxtv.zone.id/ublive.php?id=1528
Goltv,http://foxtv.zone.id/ublive.php?id=1542
Golf,http://foxtv.zone.id/ublive.php?id=1190
WWE,http://foxtv.zone.id/ublive.php?id=1191
UFC PASS,http://foxtv.zone.id/ublive.php?id=1192
ESPN U,http://foxtv.zone.id/ublive.php?id=1196
Discovery Channel,http://foxtv.zone.id/ublive.php?id=1198
National Geographic,http://foxtv.zone.id/ublive.php?id=1200
History,http://foxtv.zone.id/ublive.php?id=1204
SMITHSONIAN,http://foxtv.zone.id/ublive.php?id=1205
Disney,http://foxtv.zone.id/ublive.php?id=1208
Disney XD,http://foxtv.zone.id/ublive.php?id=1209
Nick Junior,http://foxtv.zone.id/ublive.php?id=1213
Boomerang,http://foxtv.zone.id/ublive.php?id=1214
KCBS（原CBS）,http://foxtv.zone.id/ublive.php?id=1219
LifeTime US,http://foxtv.zone.id/ublive.php?id=1226
Arts and Entertainment,http://foxtv.zone.id/ublive.php?id=1227
Hallmark,http://foxtv.zone.id/ublive.php?id=1535
WE TV,http://foxtv.zone.id/ublive.php?id=1229
VH-1,http://foxtv.zone.id/ublive.php?id=1233
OWN US,http://foxtv.zone.id/ublive.php?id=1235
GSN,http://foxtv.zone.id/ublive.php?id=1236
TVG,http://foxtv.zone.id/ublive.php?id=1543
Cooking Channel,http://foxtv.zone.id/ublive.php?id=1238
FYI,http://foxtv.zone.id/ublive.php?id=1240
BabyTV,http://foxtv.zone.id/ublive.php?id=1241
TVB1,http://foxtv.zone.id/ublive.php?id=1242
TVB DRAMA,http://foxtv.zone.id/ublive.php?id=1243
ABC News,http://foxtv.zone.id/ublive.php?id=1516
TVBJ1,http://foxtv.zone.id/ublive.php?id=1244
TVBE,http://foxtv.zone.id/ublive.php?id=1245
ktsf26,http://foxtv.zone.id/ublive.php?id=1517
The Weather Nation,http://foxtv.zone.id/ublive.php?id=1105
Cinemax,http://foxtv.zone.id/ublive.php?id=1518
History,http://foxtv.zone.id/ublive.php?id=1530
Bloomberg,http://foxtv.zone.id/ublive.php?id=1107
Fox News,http://foxtv.zone.id/ublive.php?id=1510
Fox News（備）,http://foxtv.zone.id/ublive.php?id=3263
Travel chan,http://foxtv.zone.id/ublive.php?id=1515
Discovery,http://foxtv.zone.id/ublive.php?id=1529
ShowTime 1,http://foxtv.zone.id/ublive.php?id=1114
NHL net,http://foxtv.zone.id/ublive.php?id=1534
ShowTime 2,http://foxtv.zone.id/ublive.php?id=1115
ShowCase US,http://foxtv.zone.id/ublive.php?id=1116
Starz Comedy,http://foxtv.zone.id/ublive.php?id=1118
Starz Edge,http://foxtv.zone.id/ublive.php?id=1119
Starz Kids Family,http://foxtv.zone.id/ublive.php?id=1120
World Fishing net,http://foxtv.zone.id/ublive.php?id=1531
Starz Encore,http://foxtv.zone.id/ublive.php?id=1121
Starz Encore Westerns,http://foxtv.zone.id/ublive.php?id=1122
Bravo,http://foxtv.zone.id/ublive.php?id=1525
Babytv,http://foxtv.zone.id/ublive.php?id=1522
Nat Geo,http://foxtv.zone.id/ublive.php?id=1520
WFLD-DT Fox 32.1,http://foxtv.zone.id/ublive.php?id=2431
CBS2-WBBM-TV,http://foxtv.zone.id/ublive.php?id=2822
ken5,http://foxtv.zone.id/ublive.php?id=2429
VH1,http://foxtv.zone.id/ublive.php?id=1532
woai,http://foxtv.zone.id/ublive.php?id=2430
TLC,http://foxtv.zone.id/ublive.php?id=1533
TNT,http://foxtv.zone.id/ublive.php?id=1524
ksat12,http://foxtv.zone.id/ublive.php?id=2428
Syfy,http://foxtv.zone.id/ublive.php?id=1537
加拿大,#genre#
The Weather Network,http://foxtv.zone.id/ublive.php?id=1251
CP 24 Canada,http://foxtv.zone.id/ublive.php?id=1247
CBC,http://foxtv.zone.id/ublive.php?id=1252
CTV,http://foxtv.zone.id/ublive.php?id=1253
CHCH,http://foxtv.zone.id/ublive.php?id=1256
CTV 2,http://foxtv.zone.id/ublive.php?id=1257
OMNI 1,http://foxtv.zone.id/ublive.php?id=1258
OMNI 2,http://foxtv.zone.id/ublive.php?id=1259
TVO,http://foxtv.zone.id/ublive.php?id=1260
Discovery Canada,http://foxtv.zone.id/ublive.php?id=1261
TLC Canada,http://foxtv.zone.id/ublive.php?id=1262
Love Nature,http://foxtv.zone.id/ublive.php?id=1263
Food Network Canada,http://foxtv.zone.id/ublive.php?id=1265
Cooking Channel Canada,http://foxtv.zone.id/ublive.php?id=1266
CTV Comedy,http://foxtv.zone.id/ublive.php?id=1267
CTV Sci-Fi,http://foxtv.zone.id/ublive.php?id=1268
Crave 1,http://foxtv.zone.id/ublive.php?id=1269
Crave 2,http://foxtv.zone.id/ublive.php?id=1270
Crave 3,http://foxtv.zone.id/ublive.php?id=1271
TSN 1,http://foxtv.zone.id/ublive.php?id=1273
TSN 2,http://foxtv.zone.id/ublive.php?id=1274
TSN 3,http://foxtv.zone.id/ublive.php?id=1275
TSN 4,http://foxtv.zone.id/ublive.php?id=1276
TSN 5,http://foxtv.zone.id/ublive.php?id=1277
SportNet ON,http://foxtv.zone.id/ublive.php?id=1278
SportNet One,http://foxtv.zone.id/ublive.php?id=1279
SportNet World,http://foxtv.zone.id/ublive.php?id=1280
SportNet 360,http://foxtv.zone.id/ublive.php?id=1281
NBA CA,http://foxtv.zone.id/ublive.php?id=1282
TreeHouse,http://foxtv.zone.id/ublive.php?id=1283
Teletoon,http://foxtv.zone.id/ublive.php?id=1284
YTV,http://foxtv.zone.id/ublive.php?id=1285
新時代東部,http://foxtv.zone.id/ublive.php?id=1286
（時移）新時代東,http://foxtv.zone.id/ublive.php?id=1287
新時代2,http://foxtv.zone.id/ublive.php?id=1288
城市電視,http://foxtv.zone.id/ublive.php?id=1289
Sportsnet P,http://foxtv.zone.id/ublive.php?id=3074
Global,http://foxtv.zone.id/ublive.php?id=1254
City,http://foxtv.zone.id/ublive.php?id=1255
HGTV Canada,http://foxtv.zone.id/ublive.php?id=1264
Business Network News,http://foxtv.zone.id/ublive.php?id=1250
CTV News,http://foxtv.zone.id/ublive.php?id=1249
CBC News,http://foxtv.zone.id/ublive.php?id=1248
Crave 4,http://foxtv.zone.id/ublive.php?id=1272
英國頻道,#genre#
bt espn hd,http://foxtv.zone.id/ublive.php?id=2790
GB News,http://foxtv.zone.id/ublive.php?id=77
TalkTV,http://foxtv.zone.id/ublive.php?id=309
True entertainment,http://foxtv.zone.id/ublive.php?id=1386
Discovery turbo,http://foxtv.zone.id/ublive.php?id=1387
sky_docu_hd,http://foxtv.zone.id/ublive.php?id=1388
E4,http://foxtv.zone.id/ublive.php?id=1397
Alibi,http://foxtv.zone.id/ublive.php?id=1398
5 star,http://foxtv.zone.id/ublive.php?id=1400
Itv 1,http://foxtv.zone.id/ublive.php?id=1401
Itv 2,http://foxtv.zone.id/ublive.php?id=1402
Itv 3,http://foxtv.zone.id/ublive.php?id=1403
Itv 4,http://foxtv.zone.id/ublive.php?id=1404
discovery channel,http://foxtv.zone.id/ublive.php?id=1406
Comedy Central,http://foxtv.zone.id/ublive.php?id=1408
Rte1,http://foxtv.zone.id/ublive.php?id=1409
Rte2,http://foxtv.zone.id/ublive.php?id=1410
Premiersp,http://foxtv.zone.id/ublive.php?id=1411
Freesports,http://foxtv.zone.id/ublive.php?id=1412
History,http://foxtv.zone.id/ublive.php?id=1413
CNBC,http://foxtv.zone.id/ublive.php?id=1414
Aljazeera,http://foxtv.zone.id/ublive.php?id=1415
Tv3 virgin,http://foxtv.zone.id/ublive.php?id=1416
Home,http://foxtv.zone.id/ublive.php?id=1417
Dave,http://foxtv.zone.id/ublive.php?id=1418
Film 4,http://foxtv.zone.id/ublive.php?id=1419
More 4,http://foxtv.zone.id/ublive.php?id=1420
Gold,http://foxtv.zone.id/ublive.php?id=1422
Syfy,http://foxtv.zone.id/ublive.php?id=1423
discovery science,http://foxtv.zone.id/ublive.php?id=1424
Discovery investigation,http://foxtv.zone.id/ublive.php?id=1426
Tg4,http://foxtv.zone.id/ublive.php?id=1427
Real live,http://foxtv.zone.id/ublive.php?id=1428
Cartoonito,http://foxtv.zone.id/ublive.php?id=1429
Watch,http://foxtv.zone.id/ublive.php?id=1430
Challenge,http://foxtv.zone.id/ublive.php?id=1431
Pick,http://foxtv.zone.id/ublive.php?id=1433
Nat Geo Wild,http://foxtv.zone.id/ublive.php?id=1434
Nick jr,http://foxtv.zone.id/ublive.php?id=1435
Quest,http://foxtv.zone.id/ublive.php?id=1436
Sky News,http://foxtv.zone.id/ublive.php?id=169
BT Sport 2,http://foxtv.zone.id/ublive.php?id=166
BT Sport 3,http://foxtv.zone.id/ublive.php?id=167
BT Sport 1,http://foxtv.zone.id/ublive.php?id=165
Sky Sports 1,http://foxtv.zone.id/ublive.php?id=172
Sky Sport 2,http://foxtv.zone.id/ublive.php?id=171
Sky Sport 3,http://foxtv.zone.id/ublive.php?id=183
Sky Sport 5,http://foxtv.zone.id/ublive.php?id=418
sky sports racing hd,http://foxtv.zone.id/ublive.php?id=2778
sky news hd,http://foxtv.zone.id/ublive.php?id=2779
UK Euro Sport 1,http://foxtv.zone.id/ublive.php?id=3226
UK Euro Sport 2,http://foxtv.zone.id/ublive.php?id=3227
sky sports mix,http://foxtv.zone.id/ublive.php?id=2780
sky sports arena,http://foxtv.zone.id/ublive.php?id=2781
sky sports football,http://foxtv.zone.id/ublive.php?id=2782
sky sports premier league,http://foxtv.zone.id/ublive.php?id=2783
sky sports the open,http://foxtv.zone.id/ublive.php?id=2784
sky sports action,http://foxtv.zone.id/ublive.php?id=2785
sky sports main event,http://foxtv.zone.id/ublive.php?id=2787
sky sports f1,http://foxtv.zone.id/ublive.php?id=3237
Sky Sports F1,http://foxtv.zone.id/ublive.php?id=182
cbs action,http://foxtv.zone.id/ublive.php?id=3238
Russia Today,http://foxtv.zone.id/ublive.php?id=3239
4seven hd,http://foxtv.zone.id/ublive.php?id=3240
racing uk hd,http://foxtv.zone.id/ublive.php?id=3241
sky greats,http://foxtv.zone.id/ublive.php?id=3243
channel 4 hd,http://foxtv.zone.id/ublive.php?id=3245
channel 5,http://foxtv.zone.id/ublive.php?id=3247
sony tv,http://foxtv.zone.id/ublive.php?id=3248
法國頻道,#genre#
FRANCE 24,http://foxtv.zone.id/ublive.php?id=1042
Franceinfo,http://foxtv.zone.id/ublive.php?id=376
Euronews français,http://foxtv.zone.id/ublive.php?id=1017
Boomerang,http://foxtv.zone.id/ublive.php?id=2228
CANAL Sport,http://foxtv.zone.id/ublive.php?id=2234
Cine Class,http://foxtv.zone.id/ublive.php?id=2229
Cine Permier,http://foxtv.zone.id/ublive.php?id=2237
FR Eurosport 1,http://foxtv.zone.id/ublive.php?id=2327
FR Eurosport 2,http://foxtv.zone.id/ublive.php?id=3225
Paramount,http://foxtv.zone.id/ublive.php?id=2233
Paris premiere,http://foxtv.zone.id/ublive.php?id=2235
TF1 HD,http://foxtv.zone.id/ublive.php?id=2236
Toute Lhistoire,http://foxtv.zone.id/ublive.php?id=2238
德國頻道,#genre#
Euronews,http://foxtv.zone.id/ublive.php?id=1560
Das Erste,http://foxtv.zone.id/ublive.php?id=1523
BR Fernsehen,http://foxtv.zone.id/ublive.php?id=3032
Tagesschau24,http://foxtv.zone.id/ublive.php?id=1690
SR,http://foxtv.zone.id/ublive.php?id=3220
RNF,http://foxtv.zone.id/ublive.php?id=414
Regio TV Bodensee,http://foxtv.zone.id/ublive.php?id=457
Regio TV Stuttgart,http://foxtv.zone.id/ublive.php?id=453
Regio TV Schwaben,http://foxtv.zone.id/ublive.php?id=416
LTV,http://foxtv.zone.id/ublive.php?id=407
Baden TV,http://foxtv.zone.id/ublive.php?id=412
意大利,#genre#
Euronews,http://foxtv.zone.id/ublive.php?id=186
Sky Calcio,http://foxtv.zone.id/ublive.php?id=2737
SKY SPORT NBA,http://foxtv.zone.id/ublive.php?id=2738
SKY SPORT ARENA,http://foxtv.zone.id/ublive.php?id=2739
SKY F1,http://foxtv.zone.id/ublive.php?id=2740
Sky sport uno,http://foxtv.zone.id/ublive.php?id=1597
Inter TV,http://foxtv.zone.id/ublive.php?id=1599
Deejay TV,http://foxtv.zone.id/ublive.php?id=1601
Rai Sport,http://foxtv.zone.id/ublive.php?id=1613
Italia 1,http://foxtv.zone.id/ublive.php?id=1616
Kiss Kiss,http://foxtv.zone.id/ublive.php?id=3216
新馬頻道,#genre#
CNA 24,http://foxtv.zone.id/ublive.php?id=15
AEC,http://foxtv.zone.id/ublive.php?id=433
AEC,http://foxtv.zone.id/ublive.php?id=2745
CNA Insider,http://foxtv.zone.id/ublive.php?id=3208
Channel8HD,http://foxtv.zone.id/ublive.php?id=431
TV2,http://foxtv.zone.id/ublive.php?id=436
TV3,http://foxtv.zone.id/ublive.php?id=437
TV8,http://foxtv.zone.id/ublive.php?id=442
Arena,http://foxtv.zone.id/ublive.php?id=1172
ChannelU,http://foxtv.zone.id/ublive.php?id=443
Channel8,http://foxtv.zone.id/ublive.php?id=142
Channel5HD,http://foxtv.zone.id/ublive.php?id=1930
天映頻道,http://foxtv.zone.id/ublive.php?id=441
KIX,http://foxtv.zone.id/ublive.php?id=430
全佳,http://foxtv.zone.id/ublive.php?id=427
歡喜,http://foxtv.zone.id/ublive.php?id=432
TVN,http://foxtv.zone.id/ublive.php?id=1170
華麗,http://foxtv.zone.id/ublive.php?id=429
Astro AWANI,http://foxtv.zone.id/ublive.php?id=2741
Astro Awani,http://foxtv.zone.id/ublive.php?id=440
Suria,http://foxtv.zone.id/ublive.php?id=434
TV9,http://foxtv.zone.id/ublive.php?id=438
NTV7,http://foxtv.zone.id/ublive.php?id=439
AOD,http://foxtv.zone.id/ublive.php?id=428
TV1,http://foxtv.zone.id/ublive.php?id=435
Astro Sp1,http://foxtv.zone.id/ublive.php?id=444
ASSP1_HD,http://foxtv.zone.id/ublive.php?id=1070
Astro Sp2,http://foxtv.zone.id/ublive.php?id=445
ASSP2_HD,http://foxtv.zone.id/ublive.php?id=1071
Astro Sp3,http://foxtv.zone.id/ublive.php?id=446
ASSP3_HD,http://foxtv.zone.id/ublive.php?id=1072
Astro Sp4,http://foxtv.zone.id/ublive.php?id=3234
Astro Sp4,http://foxtv.zone.id/ublive.php?id=447
BOO,http://foxtv.zone.id/ublive.php?id=1437
CCM,http://foxtv.zone.id/ublive.php?id=1438
KIX,http://foxtv.zone.id/ublive.php?id=1446
PRIMA,http://foxtv.zone.id/ublive.php?id=1448
sony_one,http://foxtv.zone.id/ublive.php?id=1451
TV8,http://foxtv.zone.id/ublive.php?id=1455
Channel5,http://foxtv.zone.id/ublive.php?id=141
AFN,http://foxtv.zone.id/ublive.php?id=195
Channel U,http://foxtv.zone.id/ublive.php?id=1077
Vasantham,http://foxtv.zone.id/ublive.php?id=1078
TVB星河,http://foxtv.zone.id/ublive.php?id=1079
TVB經典,http://foxtv.zone.id/ublive.php?id=1083
Suria,http://foxtv.zone.id/ublive.php?id=1076
OKEY,http://foxtv.zone.id/ublive.php?id=1075
AXN,http://foxtv.zone.id/ublive.php?id=1044
BNC,http://foxtv.zone.id/ublive.php?id=1045
菲律賓,#genre#
CinemaOne,http://foxtv.zone.id/ublive.php?id=1333
泰國頻道,#genre#
Channel 5,http://foxtv.zone.id/ublive.php?id=2316
Channel 7,http://foxtv.zone.id/ublive.php?id=2317
MCOT HD,http://foxtv.zone.id/ublive.php?id=2318
Gmm one,http://foxtv.zone.id/ublive.php?id=2322
Mono,http://foxtv.zone.id/ublive.php?id=2323
Thairath,http://foxtv.zone.id/ublive.php?id=2324
TPBS,http://foxtv.zone.id/ublive.php?id=2325
Workpoint,http://foxtv.zone.id/ublive.php?id=2326
Nation,http://foxtv.zone.id/ublive.php?id=2328
Tnn24,http://foxtv.zone.id/ublive.php?id=2329
Amarin,http://foxtv.zone.id/ublive.php?id=2320
PPTV,http://foxtv.zone.id/ublive.php?id=2240
PPTV,http://foxtv.zone.id/ublive.php?id=2319
Nation TV,http://foxtv.zone.id/ublive.php?id=2245
M Channel,http://foxtv.zone.id/ublive.php?id=2246
JKN,http://foxtv.zone.id/ublive.php?id=2247
Thai PBS,http://foxtv.zone.id/ublive.php?id=1047
NEWS1,http://foxtv.zone.id/ublive.php?id=1608
Channel 3,http://foxtv.zone.id/ublive.php?id=2315
Thailand ch3,http://foxtv.zone.id/ublive.php?id=1839
印尼頻道,#genre#
CNN Indonesia,http://foxtv.zone.id/ublive.php?id=1145
KOMPASTV,http://foxtv.zone.id/ublive.php?id=2577
tvOne,http://foxtv.zone.id/ublive.php?id=2734
TVRI,http://foxtv.zone.id/ublive.php?id=1473
Rcti,http://foxtv.zone.id/ublive.php?id=1474
Kompass,http://foxtv.zone.id/ublive.php?id=1475
Indosiar,http://foxtv.zone.id/ublive.php?id=1478
Antv,http://foxtv.zone.id/ublive.php?id=1479
TV9,http://foxtv.zone.id/ublive.php?id=1480
Mnctv,http://foxtv.zone.id/ublive.php?id=1481
Trans7,http://foxtv.zone.id/ublive.php?id=1482
Transtv,http://foxtv.zone.id/ublive.php?id=1483
JTV,http://foxtv.zone.id/ublive.php?id=1484
Sctv,http://foxtv.zone.id/ublive.php?id=1486
TVone,http://foxtv.zone.id/ublive.php?id=1487
BeritaSatu,http://foxtv.zone.id/ublive.php?id=1488
TVMU,http://foxtv.zone.id/ublive.php?id=1490
Rajawali TV,http://foxtv.zone.id/ublive.php?id=2942
NET TV,http://foxtv.zone.id/ublive.php?id=2943
JTV,http://foxtv.zone.id/ublive.php?id=2944
Bali TV,http://foxtv.zone.id/ublive.php?id=2945
Dunia Lain,http://foxtv.zone.id/ublive.php?id=2946
Trans TV,http://foxtv.zone.id/ublive.php?id=2947
Trans 7,http://foxtv.zone.id/ublive.php?id=2948
SCTV HD,http://foxtv.zone.id/ublive.php?id=2949
Indosiar,http://foxtv.zone.id/ublive.php?id=2950
Hope Channel,http://foxtv.zone.id/ublive.php?id=2951
Antara TV,http://foxtv.zone.id/ublive.php?id=2952
TV ONE,http://foxtv.zone.id/ublive.php?id=2953
Kompas TV,http://foxtv.zone.id/ublive.php?id=2954
TVRI,http://foxtv.zone.id/ublive.php?id=2955
CNN Indonesia,http://foxtv.zone.id/ublive.php?id=2956
Metro TV,http://foxtv.zone.id/ublive.php?id=2957
Aljazeera EN,http://foxtv.zone.id/ublive.php?id=2958
Berita Satu News,http://foxtv.zone.id/ublive.php?id=2959
DW TV Asia,http://foxtv.zone.id/ublive.php?id=2960
France 24,http://foxtv.zone.id/ublive.php?id=2961
Channel News Asia,http://foxtv.zone.id/ublive.php?id=2963
CNN Int,http://foxtv.zone.id/ublive.php?id=2964
CNBC Indonesia,http://foxtv.zone.id/ublive.php?id=2965
Metro TV HD,http://foxtv.zone.id/ublive.php?id=2966
CGTN News,http://foxtv.zone.id/ublive.php?id=2967
Thrill,http://foxtv.zone.id/ublive.php?id=2968
Celestial Movies,http://foxtv.zone.id/ublive.php?id=2969
KIX HD,http://foxtv.zone.id/ublive.php?id=2970
AXN,http://foxtv.zone.id/ublive.php?id=2971
HITS,http://foxtv.zone.id/ublive.php?id=2972
Paramount Network,http://foxtv.zone.id/ublive.php?id=2973
Hits Movies HD,http://foxtv.zone.id/ublive.php?id=2974
HBO HD,http://foxtv.zone.id/ublive.php?id=2975
HBO Hits HD,http://foxtv.zone.id/ublive.php?id=2976
HBO Family HD,http://foxtv.zone.id/ublive.php?id=2977
Rock Entertainment HD,http://foxtv.zone.id/ublive.php?id=2979
LifeTime HD,http://foxtv.zone.id/ublive.php?id=2980
HBO Signature HD,http://foxtv.zone.id/ublive.php?id=2981
Bioskop Indonesia,http://foxtv.zone.id/ublive.php?id=2982
Hits Movie SD,http://foxtv.zone.id/ublive.php?id=2983
HITS HD,http://foxtv.zone.id/ublive.php?id=2984
Hits Movies,http://foxtv.zone.id/ublive.php?id=2985
HBO FHD,http://foxtv.zone.id/ublive.php?id=2986
HBO Signature FHD,http://foxtv.zone.id/ublive.php?id=2987
Warner TV ID HD,http://foxtv.zone.id/ublive.php?id=2988
My Cinema Asia,http://foxtv.zone.id/ublive.php?id=2989
Cinemax ID,http://foxtv.zone.id/ublive.php?id=2990
HBO Hits FHD,http://foxtv.zone.id/ublive.php?id=2991
My Family Channel,http://foxtv.zone.id/ublive.php?id=2992
HBO SD,http://foxtv.zone.id/ublive.php?id=2993
HBO Hits SD,http://foxtv.zone.id/ublive.php?id=2994
HBO Signature SD,http://foxtv.zone.id/ublive.php?id=2995
HBO Family SD,http://foxtv.zone.id/ublive.php?id=2996
FLIK HD,http://foxtv.zone.id/ublive.php?id=2997
Galaxy Premium SD,http://foxtv.zone.id/ublive.php?id=2998
Galaxy SD,http://foxtv.zone.id/ublive.php?id=2999
ATV,http://foxtv.zone.id/ublive.php?id=3000
HBO Family FHD,http://foxtv.zone.id/ublive.php?id=3001
Cinemax FHD,http://foxtv.zone.id/ublive.php?id=3002
IMC SD,http://foxtv.zone.id/ublive.php?id=3003
Celestial Classic Movies CCM,http://foxtv.zone.id/ublive.php?id=3004
Discovery Channel,http://foxtv.zone.id/ublive.php?id=3005
History,http://foxtv.zone.id/ublive.php?id=3014
History,http://foxtv.zone.id/ublive.php?id=3016
Lingua Channel,http://foxtv.zone.id/ublive.php?id=3017
Da Vinci Learning,http://foxtv.zone.id/ublive.php?id=3019
Aniplus,http://foxtv.zone.id/ublive.php?id=3024
ANIMAX海外頻道,http://foxtv.zone.id/ublive.php?id=3025
My Kidz,http://foxtv.zone.id/ublive.php?id=3026
Boomerang ID,http://foxtv.zone.id/ublive.php?id=3027
Nick Jr,http://foxtv.zone.id/ublive.php?id=3029
Cartoon Network,http://foxtv.zone.id/ublive.php?id=3030
Dunia Anak,http://foxtv.zone.id/ublive.php?id=3031
My Kidz,http://foxtv.zone.id/ublive.php?id=3033
Indi Kids,http://foxtv.zone.id/ublive.php?id=3034
Horee,http://foxtv.zone.id/ublive.php?id=3035
Dream Works,http://foxtv.zone.id/ublive.php?id=3036
Golf Channel,http://foxtv.zone.id/ublive.php?id=3040
NBA 2TV,http://foxtv.zone.id/ublive.php?id=3044
Horizon Sports,http://foxtv.zone.id/ublive.php?id=3045
Fashion TV,http://foxtv.zone.id/ublive.php?id=3046
TLC HD,http://foxtv.zone.id/ublive.php?id=3047
HGTV,http://foxtv.zone.id/ublive.php?id=3048
TLC HD,http://foxtv.zone.id/ublive.php?id=3049
AFN HD,http://foxtv.zone.id/ublive.php?id=3050
Citra Drama,http://foxtv.zone.id/ublive.php?id=3051
Rock Action,http://foxtv.zone.id/ublive.php?id=3052
Insert,http://foxtv.zone.id/ublive.php?id=3053
Eat&Go,http://foxtv.zone.id/ublive.php?id=3054
idku,http://foxtv.zone.id/ublive.php?id=3055
K Plus,http://foxtv.zone.id/ublive.php?id=3057
Sony ONE,http://foxtv.zone.id/ublive.php?id=3058
TVN ID,http://foxtv.zone.id/ublive.php?id=3059
S GEM,http://foxtv.zone.id/ublive.php?id=3060
tVN Movies,http://foxtv.zone.id/ublive.php?id=3061
KBS World,http://foxtv.zone.id/ublive.php?id=3062
Drama Korea LBS,http://foxtv.zone.id/ublive.php?id=3063
MTV Music,http://foxtv.zone.id/ublive.php?id=3064
Prambors TV,http://foxtv.zone.id/ublive.php?id=3065
ONE African TV,http://foxtv.zone.id/ublive.php?id=3066
Citra Dangdut,http://foxtv.zone.id/ublive.php?id=3067
MTV LIVE HD,http://foxtv.zone.id/ublive.php?id=3068
i konser,http://foxtv.zone.id/ublive.php?id=3069
Makkah TV,http://foxtv.zone.id/ublive.php?id=3070
TV Mu,http://foxtv.zone.id/ublive.php?id=3071
NET TV,http://foxtv.zone.id/ublive.php?id=2937
ANTV,http://foxtv.zone.id/ublive.php?id=2938
SCTV,http://foxtv.zone.id/ublive.php?id=2939
Trans TV,http://foxtv.zone.id/ublive.php?id=2940
Trans 7,http://foxtv.zone.id/ublive.php?id=2941
DAAI TV,http://foxtv.zone.id/ublive.php?id=2936
越南頻道,#genre#
HTV7 HD,http://foxtv.zone.id/ublive.php?id=2251
HTV9 HD,http://foxtv.zone.id/ublive.php?id=2253
HTV1,http://foxtv.zone.id/ublive.php?id=2254
HTV2 HD,http://foxtv.zone.id/ublive.php?id=2255
Max by HBO,http://foxtv.zone.id/ublive.php?id=2261
Disney Chanel,http://foxtv.zone.id/ublive.php?id=2262
Bóng Đá TV,http://foxtv.zone.id/ublive.php?id=2263
QRT,http://foxtv.zone.id/ublive.php?id=1294
ANTV,http://foxtv.zone.id/ublive.php?id=1300
ANTV HD,http://foxtv.zone.id/ublive.php?id=1301
HBTV,http://foxtv.zone.id/ublive.php?id=1302
KienGiangTV,http://foxtv.zone.id/ublive.php?id=1309
KienGiangTV1,http://foxtv.zone.id/ublive.php?id=1310
澳洲,#genre#
ABC News Australia,http://foxtv.zone.id/ublive.php?id=2769
C44 Adelaide,http://foxtv.zone.id/ublive.php?id=31
Ticker NEWS,http://foxtv.zone.id/ublive.php?id=1399
C31 Melbourne,http://foxtv.zone.id/ublive.php?id=47
土耳其,#genre#
A SPOR,http://foxtv.zone.id/ublive.php?id=2367
TRT 1 HD,http://foxtv.zone.id/ublive.php?id=2368
SHOW TV HD,http://foxtv.zone.id/ublive.php?id=2369
STAR TV HD,http://foxtv.zone.id/ublive.php?id=2370
KANAL D HD,http://foxtv.zone.id/ublive.php?id=2371
FOX HD,http://foxtv.zone.id/ublive.php?id=2372
TV 8 HD,http://foxtv.zone.id/ublive.php?id=2373
CNN TURK HD,http://foxtv.zone.id/ublive.php?id=2374
HABER TURK HD,http://foxtv.zone.id/ublive.php?id=2375
NTV HD,http://foxtv.zone.id/ublive.php?id=2376
A HABER HD,http://foxtv.zone.id/ublive.php?id=2377
BEYAZ TV HD,http://foxtv.zone.id/ublive.php?id=2378
KANAL 7 HD,http://foxtv.zone.id/ublive.php?id=2379
KEMAL SUNAL TV HD,http://foxtv.zone.id/ublive.php?id=2380
ATV HD,http://foxtv.zone.id/ublive.php?id=2381
HALK TV HD,http://foxtv.zone.id/ublive.php?id=2382
TGRT HABER HD,http://foxtv.zone.id/ublive.php?id=2383
360 TV HD,http://foxtv.zone.id/ublive.php?id=2384
DMAX HD,http://foxtv.zone.id/ublive.php?id=2385
TRT BELGESEL HD,http://foxtv.zone.id/ublive.php?id=2386
TRT COCUK HD,http://foxtv.zone.id/ublive.php?id=2387
TRT SPOR HD,http://foxtv.zone.id/ublive.php?id=2388
ULUSAL TV,http://foxtv.zone.id/ublive.php?id=2391
巴西,#genre#
GNT,http://foxtv.zone.id/ublive.php?id=1689
Mais Globosat,http://foxtv.zone.id/ublive.php?id=1704
Rede TV,http://foxtv.zone.id/ublive.php?id=1728
Record,http://foxtv.zone.id/ublive.php?id=1746
SBT,http://foxtv.zone.id/ublive.php?id=1747
Sport TV 1,http://foxtv.zone.id/ublive.php?id=1779
Sport TV 2,http://foxtv.zone.id/ublive.php?id=1785
Sport TV 3,http://foxtv.zone.id/ublive.php?id=2135
Globo News,http://foxtv.zone.id/ublive.php?id=1489
Globo RJ,http://foxtv.zone.id/ublive.php?id=1688
Gloobinho,http://foxtv.zone.id/ublive.php?id=1684
भारत,#genre#
WION,http://foxtv.zone.id/ublive.php?id=303
ZeeNews,http://foxtv.zone.id/ublive.php?id=465
ABP Majha,http://foxtv.zone.id/ublive.php?id=1782
IndiaTV,http://foxtv.zone.id/ublive.php?id=1607
TV9 Marathi,http://foxtv.zone.id/ublive.php?id=2281
Sun TV,http://foxtv.zone.id/ublive.php?id=1458
Zee Tamil,http://foxtv.zone.id/ublive.php?id=1460
Zee Business,http://foxtv.zone.id/ublive.php?id=1461
Raj Musix,http://foxtv.zone.id/ublive.php?id=1463
Zee Actions,http://foxtv.zone.id/ublive.php?id=1464
KTV Tamil,http://foxtv.zone.id/ublive.php?id=1465
Zee TV HD,http://foxtv.zone.id/ublive.php?id=1466
Zee Cinema HD,http://foxtv.zone.id/ublive.php?id=1467
Colors HD,http://foxtv.zone.id/ublive.php?id=1468
Starplus,http://foxtv.zone.id/ublive.php?id=1469
Picture,http://foxtv.zone.id/ublive.php?id=1470
Asianet,http://foxtv.zone.id/ublive.php?id=1471
Times Now,http://foxtv.zone.id/ublive.php?id=1472
俄羅斯,#genre#
RT News,http://foxtv.zone.id/ublive.php?id=2564
RT Documentary,http://foxtv.zone.id/ublive.php?id=2611
5 KANAL,http://foxtv.zone.id/ublive.php?id=2444
TV CENTR,http://foxtv.zone.id/ublive.php?id=2451
私密頻道,#genre#
松視3,http://foxtv.zone.id/ublive.php?id=404
潘朵拉完美,http://foxtv.zone.id/ublive.php?id=410
HAPPY,http://foxtv.zone.id/ublive.php?id=2908
JStar,http://foxtv.zone.id/ublive.php?id=2909
彩虹E,http://foxtv.zone.id/ublive.php?id=406
彩虹E,http://foxtv.zone.id/ublive.php?id=2935
彩虹K,http://foxtv.zone.id/ublive.php?id=415
Brazzers TV,http://foxtv.zone.id/ublive.php?id=3076
Erox,http://foxtv.zone.id/ublive.php?id=3079
Hustler XXX TV,http://foxtv.zone.id/ublive.php?id=3087
BABES,http://foxtv.zone.id/ublive.php?id=3088
BABES UNLEASHED,http://foxtv.zone.id/ublive.php?id=3089
BAEB Perv City,http://foxtv.zone.id/ublive.php?id=3090
BRATTY SIS,http://foxtv.zone.id/ublive.php?id=3091
BRAZZERS EN ESPANOL,http://foxtv.zone.id/ublive.php?id=3092
BUSTY LOVER,http://foxtv.zone.id/ublive.php?id=3093
CUM 4K,http://foxtv.zone.id/ublive.php?id=3094
Blue Hustler,http://foxtv.zone.id/ublive.php?id=3077
潘朵拉完美,http://foxtv.zone.id/ublive.php?id=2932
Banana香蕉,http://foxtv.zone.id/ublive.php?id=2930
LOOK,http://foxtv.zone.id/ublive.php?id=2933
Redlight HD,http://foxtv.zone.id/ublive.php?id=452
極限電影,http://foxtv.zone.id/ublive.php?id=405
奥视频道2,http://foxtv.zone.id/ublive.php?id=2916
EXXXTRA SMALL,http://foxtv.zone.id/ublive.php?id=3099
DAUGHTER SWAP,http://foxtv.zone.id/ublive.php?id=3095
DEEPER,http://foxtv.zone.id/ublive.php?id=3096
DIGITAL PLAYGROUND,http://foxtv.zone.id/ublive.php?id=3097
EROTIC SPICE,http://foxtv.zone.id/ublive.php?id=3098
FAKE AGENT,http://foxtv.zone.id/ublive.php?id=3100
FAKE AGENT UK,http://foxtv.zone.id/ublive.php?id=3101
FAKE COP,http://foxtv.zone.id/ublive.php?id=3102
金丝雀,http://foxtv.zone.id/ublive.php?id=3155
波多野结衣,http://foxtv.zone.id/ublive.php?id=3158
上原亜衣,http://foxtv.zone.id/ublive.php?id=3162
天堂素人約啪,http://foxtv.zone.id/ublive.php?id=3164